### ISSUE TITLE
BatMap, BatSet and BatMap are missing methods that are present in stdlib

### ISSUE THREAD

**Issue by jabot2** [ocaml-batteries-team/batteries-included#1002]
@gasche : adding Map and Set to src/batteries_compattest.mlv yielded the following missing functions:
```
module Map = (Map : module type of Legacy.Map)
       ...
       The value `of_seq' is required but not provided
       The value `add_seq' is required but not provided
       The value `to_seq_from' is required but not provided
       The value `to_seq' is required but not provided
       The value `choose_opt' is required but not provided
       The value `max_binding_opt' is required but not provided
       The value `min_binding_opt' is required but not provided
       The value `union' is required but not provided

module Set = (Set : module type of Legacy.Set)
       ...
       The value `of_seq' is required but not provided
       The value `add_seq' is required but not provided
       The value `to_seq' is required but not provided
       The value `to_seq_from' is required but not provided
       The value `find_last_opt' is required but not provided
       The value `find_last' is required but not provided
       The value `find_first_opt' is required but not provided
       The value `find_first' is required but not provided
       The value `find_opt' is required but not provided
       The value `choose_opt' is required but not provided
       The value `max_elt_opt' is required but not provided
       The value `min_elt_opt' is required but not provided
```

Additionally, the Seq module in the stdlib has the `unfold` method, which is missing from BatSeq.

_Originally posted by @jabot2 in https://github.com/ocaml-batteries-team/batteries-included/issues/1000#issuecomment-760481028_

**Comment by jabot2** [comment]
I started some work in https://github.com/jabot2/batteries-included/tree/stdlib-compat-map-set-seq 
If all goes well i will create another PR this weekend.

**Comment by jabot2** [comment]
There is one incompatibility between Map and BatMap:
Map.update has type `key -> ('a option -> 'a option) -> 'a t -> 'a t` while BatMap.update has type key -> key -> 'a -> 'a t -> 'a t`
It seems Map.update was added in ocaml 4.06.
What is preferable in this case: backwards compatibility with previous versions of batteries-included or compatibility with the stdlib?

**Comment by jabot2** [comment]
There is a related case with `BatMap.union`.
The `union` method is present in BatMap and BatMap.PMap, but missing from BatMap.S.
This is quite lucky, because union was introduced in Stdlib.Map.S in ocaml 4.03, with an incompatible type.
So for `union` we have no incompatibility between batteries-included and stdlib, but the different Maps offered by batteries-included have different signatures :-(

**Comment by jabot2** [comment]
More incompatibilities between stdlib.Map and BatMap:
- max_binding should throw Not_found, not Invalid_argument(...)
- add should return a physically equal map if the binding is already present in the map
- remove should return a physically equal map if the map is unmodified
- update should return a physically equal map if the map is unmodified 
- filter should return a physically equal map if the predicate holds for every binding

**Comment by UnixJunkie** [comment]
I would favor 100% compatibility with the stdlib.
But, if that makes a breaking change for batteries, then this change must wait for our next major release.

**Comment by jabot2** [comment]
Should be finished
