### ISSUE TITLE
do we have a dependency graph of all the modules in batteries?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#1013]
Or is there a way to generate one?

**Comment by UnixJunkie** [comment]
partially answered by this PR: https://github.com/ocaml-batteries-team/batteries-included/pull/1015

**Comment by fccm** [comment]
```make
# Dependency Visualisation:

OCAMLDEP := ocamldep

.PHONY: deps_viz
deps_viz: deps.svg

deps.raw: $(CLANLIB_MLI_FILES)
        $(OCAMLDEP) -modules CL_*.mli > $@

deps.dot: deps.raw
        cat style1.dot > deps.dot
        ocaml dep2dot.ml deps.raw >> deps.dot
        echo "}" >> deps.dot

deps.svg: deps.dot
        dot -Tsvg $< -o  $@
```
[dep2dot.ml](https://github.com/fccm/ocaml-clanlib/blob/master/src/dep2dot.ml)

**Comment by fccm** [comment]
```
cat style1.dot > dependencies.dot
ocaml dep2dot.ml dependencies.txt >> dependencies.dot
sed -i -e 's!src/!!g' dependencies.dot
echo "}" >> dependencies.dot
dot -Tsvg dependencies.dot -o  dependencies.svg
```
The result is difficult to read.
Maybe there is a command line option to organise the boxes in a more readable way.

**Comment by UnixJunkie** [comment]
There is an ocamldoc option for dot generation (-dot).
More people have answered here:
https://discuss.ocaml.org/t/dependency-graph-of-some-ocaml-source-files/7198
There are some specific graphviz tools to make the graph more readable (tred).
