### ISSUE TITLE
Set.is_singleton

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#1040]
Hello,

Sometimes, knowing if a set is a singleton or not is important.
Using Set.cardinal for this is inefficient.
I propose to add this function to batteries' Set.

Any objections / ideas?

Regards,
F.

**Comment by UnixJunkie** [comment]
I have this code for an IntSet:
```
let is_singleton s =
  if IntSet.is_empty s then
    false
  else
    try
      let must_false = ref false in
      IntSet.iter (fun _x ->
          if !must_false then raise Not_singleton;
          must_false := true
        ) s;
      true
    with Not_singleton -> false

```

**Comment by gasche** [comment]
Why not? We have `empty`, `is_empty` and `singleton`, `is_singleton` would also make sense.

Note: in the meantime this can be implemented in constant time, on the user side, as `Set.to_seq s |> Seq.tl |> Seq.is_empty`.

**Comment by gasche** [comment]
Regarding the code: pattern-matching on the balanced tree would be simpler and faster. A singleton tree has one node with empty trees as children.

**Comment by UnixJunkie** [comment]
Pattern-matching it will be then.

**Comment by UnixJunkie** [comment]
done; thanks for the rapid feedback
