### ISSUE TITLE
BatList.modify: minor error in documentation comment

### ISSUE THREAD

**Issue by OnkV** [ocaml-batteries-team/batteries-included#1043]
https://github.com/ocaml-batteries-team/batteries-included/blob/87c96084313d60333cece3daa6d9478ace5e0276/src/batList.mliv#L672

Wrong: `to key [a] replaced with [f a].`
Correct: `to key [a] replaced with [f b].`

**Comment by gasche** [comment]
`f a` is indeed incorrect, but your suggestion is not sufficient given than `b` is not mentioned/introduced/defined anywhere in the documentation test. Would you like to send a complete proposal as a PR?
