### ISSUE TITLE
BatString.replace_all

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#1051]
We have BatString.replace; but it doesn't do a replace_all (which I guess is what people need, usually).
Also, its interface is clumsy.

**Comment by UnixJunkie** [comment]
The code would probably look like this:
```ocaml
let replace_all ~str ~sub ~by =
  let rec loop curr =
    let replaced, res = replace ~str:curr ~sub ~by in
    if not replaced then res
    else loop res in
  loop str
```

**Comment by UnixJunkie** [comment]
We have it already; badly named nreplace...

**Comment by UnixJunkie** [comment]
And with a very complex implementation, compared to what I just proposed.
I will git blame to see who wrote such code. :)

**Comment by gasche** [comment]
Your proposal would make a copy of the string for each occurrence of the pattern, so it has quadratic instead of linear complexity.

See `benchsuite/bench_nreplace.ml` for the various explorations that took place around `nreplace`.

**Comment by UnixJunkie** [comment]
Yes, I saw that the current implementation is the result of a performance benchmark contest; I will not touch it.
