### ISSUE TITLE
4.14 compatibility

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-batteries-team/batteries-included#1072]
OCaml 4.14~alpha1 is here. The standard library shouldn’t change from now on before the release.
Does anyone have time to do a release of batteries?

**Comment by UnixJunkie** [comment]
Which switch are we supposed to install, and which exact opam command will do so?
```bash
# opam switch create 4.14.0~alpha1
[ERROR] Could not resolve set of base packages:
        Sorry, no solution found: there seems to be a problem with your
        request.


Switch initialisation failed: clean up? ('n' will leave the switch partially
installed) [Y/n] y
```

**Comment by kit-ty-kate** [comment]
which version of opam do you have? Coulf you try with the latest version if that's not already the latest (2.1.2)

**Comment by UnixJunkie** [comment]
ok, I had to use this very complex command, found on discuss:
```bash
opam switch create 4.14.0~alpha1 --repositories=default,beta=git+https://github.com/ocaml/ocaml-beta-repository.git
```

**Comment by kit-ty-kate** [comment]
(it works without the complex command if you use opam 2.1)

**Comment by UnixJunkie** [comment]
Hi there; the compat tests were fixed for ocaml-4.14.
If the opam CI tests are working, we could issue a new tag.

**Comment by kit-ty-kate** [comment]
I’ve opened https://github.com/ocaml/opam-repository/pull/20538 using the archive pointing to the latest commit.
If CI is green (I believe it should) then i just need a new tag to replace the url and it will be good to go

**Comment by kit-ty-kate** [comment]
CI looks good on all platforms and compilers. To me this is ready to be tagged

**Comment by UnixJunkie** [comment]
You can use tag v3.5.0.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by UnixJunkie** [comment]
Compared to previous releases, it looks like there is some frenetic development in the stdlib.
