### ISSUE TITLE
`BatString.split_on_string` going backward is not documented

### ISSUE THREAD

**Issue by W95Psp** [ocaml-batteries-team/batteries-included#1088]
Hi,

Using `BatString.split_on_string` I expected for instance `BatString.split_on_string "//" "before///after"` to return `["before"; "/after"]`, but instead I get `["before/"; "after"]`.

This behavior is more or less documented in the code of `split_on_string_comp`: https://github.com/ocaml-batteries-team/batteries-included/blob/b00de06d750bfa79f887738f83102a20516ac3d1/src/batString.mlv#L397-L402

I think this behavior is quite unusual; if it is not to be changed, then it should at least be documented in [BatString.mliv](https://github.com/ocaml-batteries-team/batteries-included/blob/d471e24712dd1c0adb90db6894c1c721078b3934/src/batString.mliv#L791-L799).
Also, it is inconsistent with e.g. `BatString.split`: `BatString.split "before///after" "//"`, that returns `("before", "/after")`.

**Comment by UnixJunkie** [comment]
I agree this is a bug.

**Comment by UnixJunkie** [comment]
https://github.com/ocaml-batteries-team/batteries-included/pull/1089 should fix it

**Comment by UnixJunkie** [comment]
will have to advertise at next release that this is a breaking change; might break some existing code
