### ISSUE TITLE
BatIO.input_channel should have cleanup param default to true

### ISSUE THREAD

**Issue by mdekstrand** [ocaml-batteries-team/batteries-included#109]
If you need `cleanup:false` for `BatIO.input_channel`/`BatInnerIO.input_channel`, you're proably doing something wrong or at least very strange.  The default should be `true` so that IO naturally cleans things up.

This is a breaking change, so it needs to wait for 2.0.

**Comment by gasche** [comment]
Fixed by merging #671.
