### ISSUE TITLE
result of BatBitSet.inter(and intersect) is not correct in some cases

### ISSUE THREAD

**Issue by yhyoon** [ocaml-batteries-team/batteries-included#1090]
`let s1 = BatBitSet.create_full 16 (* represents {0, 1, ..., 14, 15} *)`
`let s2 = BatBitSet.create_full 8 (* represents {0, 1, ..., 6, 7} *)`
`let s3 = BatBitSet.inter s1 s2 (* expected: {0, 1, ..., 6, 7} *)`
`let _ = print_int (BatBitSet.count s3) (* expected: 8, actual: 16 *)`

The helper function `apply_set_op` may need some extra post-processing for `Inter` operation(for example, `if op = Inter && len1 > len2 then ...`)

**Comment by UnixJunkie** [comment]
If you have a PR to fix the problem, I will happily review it.

**Comment by gasche** [comment]
Thanks for the report! I proposed a fix in #1091.

**Comment by UnixJunkie** [comment]
Dear @yhyoon,
Can you confirm the fix proposed by @gasche fixes your problem?
Thanks a lot,
F.
