### ISSUE TITLE
Switch to odoc?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#1093]
Instead of ocamldoc.

Should we?

Can this be done automatically? I.e. update all the ocamldoc comments, if needed.

**Comment by UnixJunkie** [comment]
It would be nice if someone with odoc experience can comment.

**Comment by sim642** [comment]
With `dune build @doc`, it works out of the box. There's just a bunch of warnings about heading levels and custom tags.
It would make sense to make this switch together with #738.
