### ISSUE TITLE
Add dependency on dune

### ISSUE THREAD

**Issue by gridbugs** [ocaml-batteries-team/batteries-included#1102]
Batteries can be built with dune but doesn't list dune as one of its dependencies in its opam file. This means that the `opam-monorepo` tool is unable to vendor batteries, as it uses a dependency on dune as an heuristic to determine whether a package can be built with dune.

**Comment by UnixJunkie** [comment]
Not only the dependencies need to be updated, in the opam file, the build instructions and the tests too.
Plus, the fact that there is a dune lowerbound might restrict the ocaml versions where batteries compiles.

**Comment by UnixJunkie** [comment]
Currently, the dune-project file requires dune-2.7.

**Comment by UnixJunkie** [comment]
Dune 2.7.0 requires ocaml>=4.08.
Currently, batteries is compatible with ocaml>=4.02.3.

**Comment by UnixJunkie** [comment]
@sim642 would it be possible to rely on an older dune version?
Is it hard our dune-2.7 version constraint?

**Comment by UnixJunkie** [comment]
dune.1.11.4 is the latest dune version that was working with ocaml>=4.02.
If we could require only this dune version, then we would not need to bump the ocaml lowerbound that we support.

**Comment by sim642** [comment]
> @sim642 would it be possible to rely on an older dune version?
> Is it hard our dune-2.7 version constraint?

Maybe, it was that in dune-project already before my PRs and I didn't try to lower it. I somewhat doubt it could go as low as 1.11.4 though.

But that shouldn't actually be a problem: even recent versions of dune can be built on OCaml 4.02. Its version constraint is actually a disjunction, which just appears confusing on the opam website: https://github.com/ocaml/opam-repository/blob/a9fb5a379794b0d5d7f663ff3a3bed5d4672a5d3/packages/dune/dune.3.6.1/opam#L45.

**Comment by sim642** [comment]
Anyway, I think the dune dependency should only be added once dune becomes the default build system for batteries (which I still wanted to look into soon). Even having the dune dependency listed to make opam-monorepo happy, as-is it won't probably work well because the current batteries install via dune differs from the one via ocamlbuild in some incompatible details.

**Comment by gridbugs** [comment]
Ah right. Thanks for the details. Makes sense!

**Comment by gridbugs** [comment]
What about if dune was just added as a depopt? That way, nothing would change in terms of dependencies pulled when installing batteries, batteries would still be vendorable via opam-monorepo?

**Comment by UnixJunkie** [comment]
I think this would be completely fine.

**Comment by UnixJunkie** [comment]
@gridbugs please send a PR, good idea.

**Comment by gridbugs** [comment]
Here it is! https://github.com/ocaml-batteries-team/batteries-included/pull/1103

**Comment by UnixJunkie** [comment]
Let's say this was closed by https://github.com/ocaml-batteries-team/batteries-included/pull/1103
