### ISSUE TITLE
OCaml 5.1.1 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-batteries-team/batteries-included#1123]
https://discuss.ocaml.org/t/ocaml-5-1-1-incoming-breaking-change-in-the-marshal-module/13457

Batteries is one of the very few packages affected by this. Fortunetely this should only require a small 2 lines patch

**Comment by UnixJunkie** [comment]
I don't understand clearly what the problem is, neither the proposed breaking solution.
But if something has to be fixed, we will fix it.

**Comment by kit-ty-kate** [comment]
> I don't understand clearly what the problem is, neither the proposed breaking solution.

the gist of it is that the problem is 5.1 made is so that every OCaml binary required a system with libzstd installed so binary distributions would be harder and system change could break every ocaml binaries. So the solution is to detach the compression part from the stdlib.

> But if something has to be fixed, we will fix it.

btw you can test it locally using `opam switch create 5.1.1+trunk`

**Comment by UnixJunkie** [comment]
Why libzstd does not ship with the ocaml compiler then?

Can't they vendor it since Marshal relies on it now?

Marshal is critical for system programmers.
Almost all my programs rely on Marshal...

**Comment by kit-ty-kate** [comment]
> Marshal is critical for system programmers. Almost all my programs rely on Marshal...

i’m not sure what you understood of the change but they’re not removing Mashal, they’re only removing the `Compression` variant from the `extern_flags` type and the `compression_supported` function that was added in 5.1.0.

> Why libzstd does not ship with the ocaml compiler then? Can't they vendor it since Marshal relies on it now?

you can read the discussion here: https://github.com/ocaml/ocaml/issues/12562
