### ISSUE TITLE
strange interface error on 5.1.2

### ISSUE THREAD

**Issue by jmikedupont2** [ocaml-batteries-team/batteries-included#1126]
```
path                 ~/.opam/5.1.2+trunk/.opam-switch/build/batteries.3.7.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p batteries -\
j 23 @install
```

The error is
```
File "src/batGc.pp.ml", line 1:
# Error: The implementation src/batGc.pp.ml
#        does not match the interface src/.batteries_unthreaded.objs/byte/batGc.cmi:
#        The value `get_minor_free' is required but not provided
#        File "src/batGc.mli", line 278, characters 0-61: Expected declaration
                                            [...]
```

**Comment by UnixJunkie** [comment]
I guess batteries was never compiled w/ ocaml-5.1.2.
There could be some incompatibility that needs to be resolved.
Patch welcome.

**Comment by UnixJunkie** [comment]
Is this fixed by the current version v3.8.0?
It added support for ocaml-5.2.

**Comment by jmikedupont2** [comment]
maybe testing the versions in github actions would be the best way to test a bunch of different releases of ocaml?

**Comment by jmikedupont2** [comment]
https://github.com/ocaml-batteries-team/batteries-included/pull/1129

**Comment by UnixJunkie** [comment]
What is this 5.1.2 branch by the way?
It is a development branch only I understand (the opam switch is named 5.1.2+trunk).
I am running 5.1.0 currently.

**Comment by UnixJunkie** [comment]
@jmikedupont2 'make && make test' does not trigger this error in the current version of the code (v3.8.0).

**Comment by UnixJunkie** [comment]
Closing then, if your problem persists, let me know in here.
