### ISSUE TITLE
batteries 1.3.0 compilation unsuccessful ".size expression [...] does not evaluate to a constant" 

### ISSUE THREAD

**Issue by ajendrex** [ocaml-batteries-team/batteries-included#139]
Hello,

I'm trying to install batteries 1.3.0 and this is the output to 'make all' command:

cp -f src/batCamomile-0.8.2.ml src/batCamomile.ml
test ! -e src/batteries_config.ml || rm src/batteries_config.ml
ocamlbuild syntax.otarget byte.otarget src/batteries_help.cmo META shared.otarget
Finished, 0 targets (0 cached) in 00:00:00.
Warning: tag "package" does not expect a parameter, but is used with parameter "str"
- ocamlfind ocamlopt -c -annot -warn-error A -package camomile,num,str -I src -I testsuite -I qtest -I build -I libs -I libs/estring -I src/syntax/pa_comprehension -I src/syntax/pa_strings -o src/batFloat.cmx src/batFloat.ml
  /tmp/camlasma5ed4b.s: Assembler messages:
  /tmp/camlasma5ed4b.s:3218: Error: .size expression for camlBatFloat__pred_1127 does not evaluate to a constant
  /tmp/camlasma5ed4b.s:3218: Error: .size expression for camlBatFloat__succ_1125 does not evaluate to a constant
  /tmp/camlasma5ed4b.s:3218: Error: .size expression for camlBatFloat__entry does not evaluate to a constant
  File "src/batFloat.ml", line 1, characters 0-1:
  Error: Assembler error, input left in file /tmp/camlasma5ed4b.s
  Command exited with code 2.
  Compilation unsuccessful after building 417 targets (416 cached) in 00:00:01.
  make: **\* [all] Error 10

Please help me, I am a beginner in ocaml and have no idea what to do. (Actually, I may have some ideas, but they would imply to edit files that are supposed to work...)

thanks!

**Comment by AngryBirdShu** [comment]
wow!amazing!I am a Chinese girl! I want to solve my compile Error “ .size expression for does not evaluate to a constant ”，and I search on the Internet,and find this web page,this is my first time to Communicate to foreigners. so Excited!!!
