### ISSUE TITLE
BatHashtbl modify functions never resize

### ISSUE THREAD

**Issue by jj-issuu** [ocaml-batteries-team/batteries-included#560]
The functions `modify_opt` and `modify_def` in BatHashtbl never resize the hash table, so they have O(n) performance if the table is never modified through a function like `add` or `replace`. This should at the very least be documented, but resizing really must be implemented in order for those functions to be useful.

Looking at the source code, it's hard to see how to keep the non-inserting case highly efficient while also supporting resize and not depending too much on implementation details of stdlib/hashtbl.ml.

Perhaps the most robust solution is to implement  `modify_opt` and `modify_def` through the standard add/remove/replace/find functions. This makes the non-inserting cases slower but keeps all cases at O(1) average.

**Comment by UnixJunkie** [comment]
I think this is a performance bug.
But maybe it was corrected?
I see several merges related to this.

**Comment by jj-issuu** [comment]
I think the changes in #603 optimized this code so much that it can't be considered a performance bug. There's still room for improvement, but that would come at a high cost in code complexity and dependence on how Hashtbl is implemented in the standard library.
IMHO, this issue can be closed.

**Comment by UnixJunkie** [comment]
Thanks for the feedback.
