### ISSUE TITLE
improve `Queue.filter`

### ISSUE THREAD

**Issue by gasche** [ocaml-batteries-team/batteries-included#591]
@madroach introduced Queue.filter in GPR #585 , but when I went over the changelog to prepare the 2.3.0 release I had reservations about it, and disabled it for the release: 791278afd955dfad665ccc7db8958dabd4c81103

> I have doubts about the Queue.filter interface, which is imperative:
>   `filter : ('a -> bool) -> 'a t -> unit`
>
> While that makes sense as a mutable operation on the Queue datatype,
the fact is that all `filter` functions (including for mutable
data-structures such as Dllist and Dynarray) return a filtered copy of
their datatype instead of mutating in place. This convention is used
by the pa_comprehension syntax extension that will happily generate
calls to filter for any data-structure module it is given, expecting
this interface.
>
> Maybe we should consider having both
>    `filter : ('a -> bool) -> 'a t -> 'a t`
>    `filter_in_place : ('a -> bool) -> 'a t -> unit`

I will re-enable `Queue.filter` as-is as soon as I'm done with the release work, but I'd like to get more opinions on this. Should it stay as it is? What about the proposed `filter, filter_in_place` duo? Other suggestions?

**Comment by UnixJunkie** [comment]
I guess this can be closed, no?
