### ISSUE TITLE
how to turn on the syntax extension for list comprehensions?

### ISSUE THREAD

**Issue by jthale76** [ocaml-batteries-team/batteries-included#608]
Hi I have batteries 2.3.1 installed on OS X via opam and am able to get the Euler001 example to work in the toplevel (example from the Getting Started page).  However, the pythagorean triples example does not work. I don't see batteries.pa_comprehension.syntax in the output of ocamlfind's #list command.  Did it get installed? How can I turn it on?

**Comment by jthale76** [comment]
By "not work" I mean:

```
# #require "batteries.pa_comprehension.syntax";;
No such package: batteries.pa_comprehension.syntax
# let pythagorean_triples n =
    [? (a,b,c) | a <- 1--n; b <- a--n; c <- b--n; a*a + b*b = c*c ?]
  ;;
Error: Syntax error
```

**Comment by Drup** [comment]
pa_comprehension is not part of batteries anymore. Use https://bitbucket.org/cakeplus/pa_comprehension/

It's in opam as `pa_comprehension`.

**Comment by jthale76** [comment]
Thank you!
