### ISSUE TITLE
Segmentation fault when using Hashtbl?

### ISSUE THREAD

**Issue by martin-neuhaeusser** [ocaml-batteries-team/batteries-included#609]
Dear all,

first of all, I would like to thank you for this great piece of software.

I suspect a bug in the functorial version of the Hashtbl module:
The following code results in a segmentation fault on my system
(64 bit Debian, OCaml 4.02.1 and Batteries Included 2.3.1):

```ocaml
open Batteries

module Item = struct
  type t = int

  let hash t = t
  let equal = (=)
end

module H = Hashtbl.Make (Item)

let _ =
  let h = H.create 7 in
  H.replace h (-4611686018427387904) [];
  H.find_default h (-4611686018427387903) []
```

It seems as if Hashtbl does not handle a hash value that equals min_int correctly 
on all instances (note the identity function for the hash operation in the Item module).

**Comment by UnixJunkie** [comment]
It also happens with OCaml 4.01.0 and batteries 2.3.1.

**Comment by UnixJunkie** [comment]
https://gist.github.com/UnixJunkie/e7026718ceb2aa1d398a

**Comment by UnixJunkie** [comment]
in my case, only a bytecode version of the program or running it in the interpreter crashes.
A native executable works fine in my environment.

**Comment by martin-neuhaeusser** [comment]
In my setup, both a native and a byte-code compile crash.

**Comment by gasche** [comment]
I have a preliminary fix in [a fixhashtbl branch](https://github.com/ocaml-batteries-team/batteries-included/compare/master...gasche:fixhashtbl).

**Comment by martin-neuhaeusser** [comment]
Thanks for the patch! It fixes the segmentation fault in my original example.
However, it introduces a new (probably more severe) bug:

```ocaml
open Batteries

module Item = struct
  type t = int

  let hash t = t
  let equal = (=)
end

module H = Hashtbl.Make (Item)

let _ =
  let h = H.create 7 in
  H.add h 0 [];
  H.remove_all h 0;
  assert(not (H.mem h 0))
```

The assertion does not hold, i.e. with the patch, the hashtable does not remove item 0 correctly.

**Comment by gasche** [comment]
Sorry for being silent for so long on this issue -- I hadn't much time for Batteries development in the past months.

I updated my [fixhashtbl branch](https://github.com/ocaml-batteries-team/batteries-included/compare/master...gasche:fixhashtbl) to fix the ([very silly](https://github.com/ocaml-batteries-team/batteries-included/commit/426a90c360034684edc47423b964d1377db839a7)) issue with my previous patch.

@martin-neuhaeusser , would you be able to test the resulting branch again? If it works, I would like to do a bugfix release shortly.

**Comment by martin-neuhaeusser** [comment]
I removed the work-around for the bug in our project and ran our test-suite with the new version. Everything looks fine. Also, both examples work correctly.
However, I do not fully understand some details in the patch:

1. Why is the index sometimes computed by a modulo operation and at other times,
by logically conjoining the hash value with (size of the array - 1)? 
Is there an invariant saying that the number of elements in a hashtable's array is 
a power of 2? 

2. Why is the MSB masked out in lines 62 and 64? According to the documentation, Hashtbl.hash
guarantees a non-negative return value. In lines 60 and 61, this is not done.

**Comment by gasche** [comment]
Those are actually excellent questions and it is obvious in retrospect that I should add a comment explaining what is happening here.

First, some context -- you may know it already, but it doesn't hurt to explain it all in one place.

The implementation of `BatHashtbl` does something ugly: we break open the abstraction of the stdlib's `Hashtbl` module. This is necessary if we want to be able to extend the implementation with new features relying on internal representation, yet preserve compatibility between the types `BatHashtbl.t` and `Hashtbl.t` (which is necessary to support the workflow of users using `Hashtbl` functions when they exist, and only defaulting on `BatHashtbl` in the other case). We could just copy-paste the `Hashtbl` implementation and live our own life (as we did for `BatMap`), but then the types would be distinct. So the code is tightly bound to the evolution of the upstream compiler library.

In OCaml 4.00, the OCaml stdlib completely changed its hash function implementation, but used a trick to be able to still handle hash tables in the old format (if e.g. you had serialized values lying around from the previous OCaml version, loaded under the new version): the `if Obj.size ...` test is used to know if we are manipulating "old hash tables" and "new hash tables".

The `>=4` implementation guarantees that the bucket array length is always a power of 2, so `land` can be used, while the `<4` implementation allows arbitrary sizes (it takes the input size given by the user) so it uses modulo.

Regarding your second question: I'm actually not sure anymore why this `land max_int` is done -- both the old and the new implementation do that at the C level already. I think this comes from the code for `Hashtbl.Make`, which cannot make such an assumption and thus needs to ensure positivity (the `<4` upstream implementation does use `land max_int` for this). So thanks for the question, I'll iterate on this patch one more time to see if these checks can be removed.

**Comment by UnixJunkie** [comment]
Is the fix for this merged?
Is there something that needs to be tested?

**Comment by gasche** [comment]
I haven't had time to look at a definitive answer for @martin-neuhaeusser 's question above:

> Why is the MSB masked out in lines 62 and 64? According to the documentation, Hashtbl.hash
guarantees a non-negative return value. In lines 60 and 61, this is not done.

I think the patch is correct and can be safely applied for the coming release, but it may be possible to remove a useless operation if one can indeed check that it is useless.

**Comment by UnixJunkie** [comment]
The lines in question (62, 64, 60 and 61) are from which file?

**Comment by gasche** [comment]
Those would be in [the post-patch version of batHashtbl.mlv](https://github.com/gasche/batteries-included/blob/4773ed2ce0ae46232e129bfc8dcdb18b877c7741/src/batHashtbl.mlv#L62-L64).

**Comment by UnixJunkie** [comment]
Is there a pull request with the patch?

**Comment by gasche** [comment]
Sorry for the noise. The branch is now submitted as pull request #647 .
