### ISSUE TITLE
I'd like a BatSet.to_array

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#611]
I was surprised there is not one already.
If I use to_list then List.to_array I go twice through the data while
there is no need in my case.

**Comment by gasche** [comment]
You could also use `Array.of_enum (S.enum set)`, but it has to go twice through the structure to get the size anyway. You could try to iterate `DynArray.add` and then `DynArray.to_array` as a single-traversal alternative (or maybe you can keep the obtained `DynArray` in the end?).

**Comment by UnixJunkie** [comment]
Interesting module DynArray, I didn't know we have it.

**Comment by UnixJunkie** [comment]
I provided one here:
https://github.com/ocaml-batteries-team/batteries-included/pull/620

**Comment by UnixJunkie** [comment]
There is also an of_array on top of it here:
https://github.com/ocaml-batteries-team/batteries-included/pull/621

**Comment by gasche** [comment]
Closing, as both PRs have been merged. Thanks!
