### ISSUE TITLE
 I'd like a BatSet.nth

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#612]
Like List.nth: get the element at the given rank or raise Invalid_argument

**Comment by UnixJunkie** [comment]
Of course, I can implement it, if deemed useful.

**Comment by gasche** [comment]
Feel free to, that seems like a natural feature to have. Maybe we could only have `nth_exn` and `nth_opt`, and not have to decide on whether `nth` should raise an exception or not?

**Comment by UnixJunkie** [comment]
OK, I will add at_exn (I just read in BatList nth is depecrated), then wrap it to provide at_opt.

**Comment by UnixJunkie** [comment]
My current trial can be seen here:
https://github.com/UnixJunkie/batteries-included/commit/3c13367c3bff79dd24a0a7bb616c61af7227f6e1

**Comment by UnixJunkie** [comment]
the final proposal is here:
https://github.com/ocaml-batteries-team/batteries-included/pull/616

**Comment by UnixJunkie** [comment]
at_rank_exn was accepted
