### ISSUE TITLE
Map.pop_min and Map.pop_max

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#622]
must do what Set.pop_min/max do

**Comment by UnixJunkie** [comment]
I can start working on this when all the work I did in sets is accepted: update, pop_min, pop_max and at_rank_exn.
I will reflect all those in Map.

**Comment by UnixJunkie** [comment]
We must also have Map.at_rank_exn and Map.update to reflect fully BatSet

**Comment by UnixJunkie** [comment]
I'm tired and this does not compile
https://github.com/UnixJunkie/batteries-included/tree/map_pop_min
is there anyone with an idea?
I guess it's a problem with a .mli or so.

**Comment by UnixJunkie** [comment]
https://gist.github.com/UnixJunkie/23248b0f9d505bb2a0ce

**Comment by gasche** [comment]
The branch `map_pop_min` at commit de721282a5bcd2de72 seems to compile fine on my machine.

**Comment by gasche** [comment]
@UnixJunkie , any news? I would like to do a bugfix release not too far from now, and in the current state I would be hesitating between implementing the `batMap` counterparts myself, or not including the `batSet` changes.

**Comment by UnixJunkie** [comment]
Unfortunately, I don't have more code to send.
I have a deadline in September so I must work on other things.

**Comment by gasche** [comment]
No problem -- it's useful to have the information. I'll see what I do depending on my time available when preparing the release.

**Comment by UnixJunkie** [comment]
They have been implemented in BatMap.
