### ISSUE TITLE
Would it be doable to get rid of the implementation of BatMap?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#629]
I think there is a lot of code duplication between BatMap and BatSet
and I wonder if all operations of the BatMap could not be implemented with
a carefully created set.

**Comment by gasche** [comment]
Either that or the other way around: implement sets as unit-holding maps. But that would be too costly from a performance point of view, I'm afraid. I agree that the duplication makes it a bit harder to implement functions while keeping the interfaces in synch, but it is also a part of the code that is very robust (very few bugs against it), so the maintenance cost is reasonable despite the duplication.

**Comment by UnixJunkie** [comment]
Where would the performance cost come from?
Both data structures documentation say they use balanced binary trees.
