### ISSUE TITLE
we should make a release

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#641]
Where is the TODO list for this by the way?

**Comment by c-cube** [comment]
i'ts in `howto/release.md`.

**Comment by UnixJunkie** [comment]
Thanks, I'll try to work on it at home.

**Comment by UnixJunkie** [comment]
the next step is to do the changelog

**Comment by gasche** [comment]
I think we do need to make a decision on #647 before the release : either merge as is, or think harder about a change in the patch. I can try to do either that or the Changelog, do you have a preference?

**Comment by UnixJunkie** [comment]
I am OK with a merge as is (because our release starts to be long overdue).
The code in Hashtbl is tricky so I don't like it.
Usually, I don't fix tricky code: I rewrite it (to something I find clear).
However, I don't plan to become an expert of the Hashtbl module, so I will not rewrite
code in it anytime soon.
Currently, I only know to some extent the batteries modules Set and List because I use
them heavily so I need sometimes new efficient operations in them.
If you can provide what you consider the definitive patch to close issue #647 soon, please do it.
I should send some proposal for the changelog before next monday.

**Comment by UnixJunkie** [comment]
There is the long changelog from the previous tag in there:
https://github.com/UnixJunkie/batteries-included/blob/changelog_2.4.0/logs_since_release_2.3.1
I may shrink it tomorrow and send a proposal for the changelog update.

**Comment by UnixJunkie** [comment]
if and when the changelog update pull request is merged, then we can tag

**Comment by UnixJunkie** [comment]
Is it OK to tak now as v2.4.0 ?
The howto says: "change ocamlfind dependencies in META if necessary".
If we don't need to do that then it should be OK to tag.

**Comment by gasche** [comment]
There are three `@since NEXT_RELEASE` remaining in the directory. Could you fix them? Then you can tag the release. I'll write a short announce for you to send on caml-list :-)

**Comment by gasche** [comment]
```
# ANN: Batteries 2.4.0

Batteries (OCaml Batteries Included) is a community-developed overlay
over the "standard" library distributed with the compiler, that aims
to provide general-purpose data-structures and convenient functions.

The project follows a semantic versioning scheme; the new version is
backward-compatible with the previous releases (2.3.0 was in September
2014). The lowest OCaml version certainly supported is 3.12.1.

The new release is available in OPAM, or as a tarball
  https://github.com/ocaml-batteries-team/batteries-included/releases/tag/v2.4.0
or from the sources
  https://github.com/ocaml-batteries-team/batteries-included
The online API documentation is at:
  http://ocaml-batteries-team.github.io/batteries-included/hdoc2/

This release contains a handful of new functions and bugfixes -- see
the detailed changelog below. Two highlights are the `pop_{min,max}`
in BatSet and `pop_{min,max}_bindings` in BatMap contributed by
François Berenger, and a nasty bug when hashing values close to
min_int spotted by Martin Neuhäußer -- this long-hidden bug was due to
a mistake in the backward-compatibility code for the hashing function
transition between OCaml 3.12 and OCaml 4.00.

With many thanks to the contributors to this new release, including
Guillaume Allais, Aleksey Z. Arens, Nils Becker, François Berenger,
Sang Kil Cha, Simon Cruanes, Bob Fang fdopen, Anders Fugmann, Rudi
Grinberg, Herry, Christoph Höger, Max Mouratov, Martin R. Neuhäußer,
Gabriel Scherer, Quentin Stievenart, Kevin Brubeck Unhammer, Ralf
Vogler, and Xavier Van de Woestyne.

The OCaml batteries-included team.

# Detailed changelog

- BatBitSet: use Bytes instead of String
  (Gabriel Scherer)
- BatHashtbl: fix hash computation bug introduced by 4.01 (issue #609)
  (Gabriel Scherer, report by Martin R. Neuhäußer)
- BatText: synchronize nsplit to match BatString.nsplit
  (Gabriel Scherer)
- BatLazyList: fix remove_all_such documentation
  (Xavier Van de Woestyne)
- BatMap: add pop_min_binding: 'a t -> (key * 'a) * 'a t
	  and pop_max_binding: 'a t -> (key * 'a) * 'a t
  (Francois Berenger)
- BatMap: add at_rank_exn: int -> ('key, 'a) t -> ('key * 'a)
	  and update: key -> key -> 'a -> 'a t -> 'a t
  (Francois Berenger)
- BatEnum: add interleave: 'a t array -> 'a t
  (Aleksey Z. Arens)
- BatFormat: expose asprintf for V>=4.01
  (Ralf Vogler)
- BatSet: add at_rank_exn: int -> t -> elt
	  and update: elt -> elt -> t -> t
  (Francois Berenger)
- BatUTF8: add enum: t -> BatUChar.t BatEnum.t
  (Kevin Brubeck Unhammer)
- BatSet: add to_array: t -> elt array
	  and of_array: elt array -> t
	  and test for to_list
  (Francois Berenger)
- BatSet: add pop_max: 'a t -> 'a * 'a t
	  and pop_min: 'a t -> 'a * 'a t
  (Francois Berenger)
- BatSplay: hardened against read-only-data compiler optimization
  (Gabriel Scherer)
- BatList: simplified interleave implementation
  (Francois Berenger)
- BatOption: add Infix.(>>=): 'a option -> ('a -> 'b option) -> 'b option
  (Herry Herry)
- BatHashtbl: modify now have same semantics than replace for the key
  (Anders Fugmann)
- BatHashtbl: more efficient modify_opt and modify_def
  (Anders Fugmann)
- BatFormat: add pp_print_list: ?pp_sep:(formatter -> unit -> unit) ->
	                        (formatter -> 'a -> unit) ->
	                        (formatter -> 'a list -> unit)
	     and pp_print_text: formatter -> string -> unit
  (Christoph Höger)
- BatEnum: add uniq_by: ('a -> 'a -> bool) -> 'a t -> 'a t
	   and uniqq: 'a t -> 'a t
  (Max Mouratov)
- BatEnum: fix uniq to use structural comparison
  (Max Mouratov)
- BatUnix: add run_and_read: string -> process_status * string
  (Francois Berenger)
- BatCache: use hashmap to speed up lru_cache
  (Sang Kil Cha)
- BatQueue: add filter: ('a -> bool) -> 'a t -> 'a t
	    and filter_inplace: ('a -> bool) -> 'a t -> unit
	    and filter_map: ('a -> 'b option) -> 'a t -> 'b t
  (Gabriel Scherer)
```

**Comment by c-cube** [comment]
I'm not sure you should cite me, I don't remember contributing recently ^^

**Comment by gasche** [comment]
Are you saying you would prefer *not* to be cited? Because you definitely contributed since the v2.3.1 release. (And not just during the batteries-light weekend session.)

```
Simon Cruanes (5):
      Set.Make2 for functorial cartesian product
      infix operators for Set (issue #250)
      do not expose input sets in Set.Product, just their signature
      tests for set product functor
      use consistent, dot-suffixed, infixed operators
```

I'll update my message above to mention 2.3.1, rather than 2.3.0, as last release.

**Comment by c-cube** [comment]
Oh right, sorry, I did not realize it had been that long since the last release ^^. Sorry for interrupting.

**Comment by UnixJunkie** [comment]
I cannot upload the tarball to the ocamlforge neither upload the doc: I don't have the rights for that.

**Comment by gasche** [comment]
I gave you the permissions -- let me know if something does not work.

**Comment by UnixJunkie** [comment]
I cannot upload the tarball to ocamlforge. I guess it either needs admin rights or I did not find the right link.

**Comment by gasche** [comment]
Did you upload the documentation? There remain three occurences of `@since NEXT_RELEASE` in batMap.mli, could you fix them and re-upload the documentation? (No need to change the tag if you already have done it, or the release archive, this is minor, but fixing the online documentation is important.)

**Comment by gasche** [comment]
I gave you the admin rights. Sorry for not thinking of this in the first place!

**Comment by UnixJunkie** [comment]
How to upload the documentation? It's not on the forge this one, it's on github apparently.
Sorry for the NEXT_RELEASE tags; I had done it locally but not commit and pushed.

**Comment by gasche** [comment]
There is a `make upload-docs` target in the Makefile, described in the release howto.

**Comment by UnixJunkie** [comment]
OK, I pushed the corresponding branch gh-pages that it generated.

**Comment by UnixJunkie** [comment]
I am waiting for the opam package pull request to be OK with Travis before sending the release e-mail.
https://travis-ci.org/ocaml/opam-repository/builds/96942500

**Comment by gasche** [comment]
Thanks! Congratulation for handling the release so well :-)

**Comment by UnixJunkie** [comment]
There are two failures in Travis. :(
 [ERROR] No package matches batteries.2.4.0.
https://travis-ci.org/ocaml/opam-repository/jobs/96942506
# File "src/batteries.ml", line 175, characters 0-21:
# Error: Multiple definition of the type name result.
https://travis-ci.org/ocaml/opam-repository/jobs/96942505

**Comment by gasche** [comment]
Well batteries 2.4 is not compatible with OCaml trunk as it defines its own `result` type, which uses different constructor names from the one that was introduced in OCaml 4.03 (we have used `Ok/Bad` instead of `Ok/Error`). There is little that we can do except marking in opam our version constraints as `< 4.03`. We should also think of a way to support 4.03's `result` for a future Batteries release, but you cannot solve all problems at once.

(One option for example would be to have several `result` types, one from pervasives and one, deprecated, in `BatPervasives`; if we open instead of include-ing, we should be able to not break at compile-time, and then let type-directed disambiguation do the work.)

**Comment by UnixJunkie** [comment]
Thanks, it explains the second error.
I am still puzzled by the first one. I will ask opam package specialists.

**Comment by UnixJunkie** [comment]
done

**Comment by gasche** [comment]
Congratulations! Now you should start thinking of the *next* release... :-)

And I'm only half-joking. Users have repeatedly asked us to do more frequent releases, and I have personally deeply failed at making this happen. If we could get in the habits of releasing every few months (with bugfix releases more often), I think that would be very nice.

**Comment by UnixJunkie** [comment]
I am personally interested into adding the conversion functions to/from the sequence library
of @c-cube . Also, I'd like to see his proposal of batteries cut into independent pieces so that people
don't need to always depend on the whole batteries.

**Comment by gasche** [comment]
The to/from functions are easy to add and I'm strongly in favor -- I would do it yourself if you don't have time to. (I discussed last ICFP with some Batteries users that were also interested in this).

The batteries-light change is more invasive and difficult. I'm in favor of it, and possibly of breaking compatibility and aiming for 3.0 for this feature, if it can make our lives implementing it easier. Go for it, but be warned that it is more difficult than it looks like -- we may need an incremental approach rather than trying to do all in one change.

We must also prepare for the `result` type in the coming OCaml release: it is incompatible with ours, how are we going to handle this? This might be another reason for releasing a 3.0 version. (We could try to have two result types and remain backward-compatible on OCaml versions with type-directed constructor disambiguation, but which type to use in our APIs?)

Another thing that I have on my mental TODO-list for Batteries is to finish the move to `-safe-string`. (I did a patch for Extlib that apparently became lost in the limbos.)

**Comment by c-cube** [comment]
Congrats for the new release! :)
Have you had troubles with the howto?

I was going to say that version-dependent preprocessing was enough for `result`, but indeed the error version differs. 3.0 it is then? ^^

@UnixJunkie you can take a look at batteries-light (the branch is still [there](https://github.com/c-cube/batteries-included/tree/batteries-light), or the [v3-alpha](https://github.com/c-cube/batteries-included/tree/v3-alpha)), I did most of the `sequence` converters (and throw away `Enum`, which is arguably a totally orthogonal change that may not be relevant right now).

**Comment by UnixJunkie** [comment]
The howto was very useful, I improved it a little maybe.

**Comment by UnixJunkie** [comment]
I am also interested in getting rid of the .mlv/.mliv files.
I would prefer only .ml/.mli files with a standard preprocessor for ocaml.

**Comment by c-cube** [comment]
I would recommend cppo, I've been using it in containers and it works fine. There is a bit of [magic](https://github.com/c-cube/ocaml-containers/blob/master/myocamlbuild.ml#L683) for the `myocamlbuild.ml` though (or maybe an ocamlbuild plugin?).

**Comment by gasche** [comment]
I'm fine with `cppo` as well. The `.mlv` preprocessor works well enough that I've never bothered to change, but if someone else is motivated to do the work...
