### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#642]
random seed: 156550782
    \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    Error: >mid>src/batInt.ml:162
    
    Failure("law src/batInt.ml:162:  \n\n  (Q.pair Q.int Q.int) (fun (a,b) -> \n    let m = mid a b in \n    a <= b ==> (a <= m && m <= b && abs ((m-a) - (b-m)) <= 1) && \n    b < a ==> (b <= m && m <= a && abs ((m-b) - (a-m)) <= 1))\n\n failed on 1 cases. Ex: (1094452460013516131, 3281843094753857183)")
    ///////////////////////////////////////////////////////////////////////////////
    Ran: 1169 tests in: 18.27 seconds.                                        
    WARNING! SOME TESTS ARE NEITHER SUCCESSES NOR FAILURES!
    make: *** [test-byte] Error 1

**Comment by UnixJunkie** [comment]
I wonder if it's because of my compiler version: 4.02.3.
I cannot even compile tests (make test) with an older compiler:
4.01.0 && make test --> Reference to undefined global `Bytes'

**Comment by c-cube** [comment]
you can use `base-bytes` on older versions.

**Comment by UnixJunkie** [comment]
I had it installed and it wasn't compiling ?!

**Comment by c-cube** [comment]
you need to use it in the build system, like any other library.

**Comment by UnixJunkie** [comment]
The original quick check test:

    (Q.pair Q.int Q.int) (fun (a,b) -> \
    let m = mid a b in \
    a <= b ==> (a <= m && m <= b && abs ((m-a) - (b-m)) <= 1) && \
    b < a ==> (b <= m && m <= a && abs ((m-b) - (a-m)) <= 1))

My trial:

    (Q.pair Q.int Q.int) (fun (a,b) -> \
    let m = mid a b in \
    (a <= b ==> (a <= m && m <= b && abs ((m-a) - (b-m)) <= 1)))
    (Q.pair Q.int Q.int) (fun (a,b) -> \
    let m = mid a b in \
    (b < a ==> (b <= m && m <= a && abs ((m-b) - (a-m)) <= 1)))

Works while I think they are semantically the same.
I am puzzled.

**Comment by UnixJunkie** [comment]
@vincent-hugot any hint?

**Comment by c-cube** [comment]
Oh, it might be because I changed `==>` in the last iTeML (cf https://github.com/vincent-hugot/iTeML/blob/master/qtest/quickcheck.ml). It used to be a pure boolean implication, and now it raises a hidden exception if the precondition fails. The rationale is that the exceptions allows to know whether the test failed or whether it was trivial (in the last case, to try harder to generate non-trivial inputs).

**Comment by c-cube** [comment]
I think we discussed it with @gasche, too. Cf https://github.com/vincent-hugot/iTeML/pull/19 (mentions of `==>` are easy to find).

**Comment by UnixJunkie** [comment]
OK, so the fix is indeed to accept my rewrite of the quick check test if I understand correctly.

**Comment by vincent-hugot** [comment]
Better to get rid of ==> entirely, I think.

**Comment by UnixJunkie** [comment]
I guess I can replace it with && in my rewrite.

**Comment by vincent-hugot** [comment]
Or define a (=>) with the old semantics and use that...

**Comment by UnixJunkie** [comment]
Corrected in my branch prepare_release branch by commit 5e648a730111ab7ce2f8ffd10330ca955231de32.
And there is already a pull request for it.
