### ISSUE TITLE
make test don't compile with qtest 2.1.0

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#649]
File "src/batAvlTree.ml", line 105, characters 39-401:
    Error: This expression has type Random.State.t -> unit
           but an expression was expected of type unit

**Comment by UnixJunkie** [comment]
@c-cube someone broke backward compatibility of qtest again ? ;^)

**Comment by c-cube** [comment]
On b37c4a1 with a fresh clone, `make test` works for me...

**Comment by UnixJunkie** [comment]
I am using compiler 4.02.3 and qtest 2.1.0.

**Comment by c-cube** [comment]
Same. Can you try to clone the repo somewhere else and repeat the test in the clone?

**Comment by UnixJunkie** [comment]
Yeah, it worked that way ... strange git behavior :(

**Comment by c-cube** [comment]
I suspect there were some leftover files somewhere (an old generated `qtest` file, maybe?)
