### ISSUE TITLE
Improve BitSet.count_array

### ISSUE THREAD

**Issue by Chimrod** [ocaml-batteries-team/batteries-included#663]
The function BitSet.count_array use a recursion to sum each byte in the char. This is as efficient as an iteration over each of them.

This code (inspired by H. Warren's Hackers's deligth) only use bit operation, without jump :

```ocaml
let count_array =
  let count_bits i =
  let mask1 = 0b01010101
  and mask2 = 0b00110011
  and mask3 = 0b00001111
  in
    let s1 = (i land mask1) + ((i lsr 1) land mask1) in
    let s2 = (s1 land mask2) + ((s1 lsr 2) land mask2) in
    (s2 land mask3) + ((s2 lsr 4) land mask3)
    in
  Array.init 256 count_bits
```

(It assumes that the integer i is ranged between 0 and 255, according to Char.code result)

**Comment by gasche** [comment]
I believe that the performances of `count_array` do not matter, as it is a precomputation that occurs exactly once when the user program start, used to fill a table that is then used by the `BitSet.count` function to compute any bitset count. If this precomputation proved to be an issue in terms of performance, we could instead replace it by a constant array (of size 256).

It could be interesting to use your code if we could replace the table lookup in `count` by your optimization, but I am skeptical this would be interesting performance-wise.

**Comment by Chimrod** [comment]
The only acceptable solution for bypass the table lookup requires to iterate over the Bytes array by step of « n chars » instead of char by char. But there is no native way to do this, and I do not think that the overload for writing in OCaml worth it…

**Comment by gasche** [comment]
I think that this would in fact be possible; the pattern-matching compiler does that when it has strings to compare (this work was contributed by Benoît Vaugon), but I am not sure this capacity is exposed to user programs currently. If you were interested in making that happen, we could try to poke and ask compiler maintainers, but I think it would help to have a concrete use-case to justify the work. Do you have an OCaml program for which the performance of this `count` operation is critical?

(Do you agree with my assessment of your current patch? I think that by itself it is not really worth the extra code complexity.)

**Comment by Chimrod** [comment]
I agree with you that this only a minor performance gain (and I do not require extra performances which could justify a change in the compiler). 

But with two equivalents code, I think that a general purpose library should consider to take the better one. Especially when the code is not trivial.

**Comment by gasche** [comment]
I won't merge code that I don't understand if it makes no performance difference. "Simple and obviously correct" is better than "tricky and fast" when speed does not matter.

**Comment by Chimrod** [comment]
ok. I'm closing the issue.

**Comment by UnixJunkie** [comment]
But thanks for the proposal. Also, you made me learn about the format 0b... which I find much more readable than hexadecimal, so that's cool. :)

**Comment by gasche** [comment]
Indeed; I also think this is good work and would add to the thanks -- I'm always glad when people contribute!
