### ISSUE TITLE
BatInt64 doesn't seem to contain a 'max' or 'min' function

### ISSUE THREAD

**Issue by KasperJanssens** [ocaml-batteries-team/batteries-included#664]
Is there a reason for this?

**Comment by gasche** [comment]
I don't think there is a good reason. If you want to send a PR to add these, you are welcome; see `BatInt.ml` for unit tests that you could reuse.

Another approach would be to add these functions to the the `BatNumber.Numeric` signature, which would make them available for all numeric types.

**Comment by UnixJunkie** [comment]
@KasperJanssens there is a PR filling in the bits. This could/should have been merged already.

**Comment by KasperJanssens** [comment]
Alright, we're no longer depending on this feature though could be again in the future. As far as I'm concerned you can close this issue, if it's merged in and all...
