### ISSUE TITLE
remove the old documentation

### ISSUE THREAD

**Issue by c-cube** [ocaml-batteries-team/batteries-included#666]
The documentation for batteries 1 is still around, still well ranked in google, and it looks like many people (beginners) are confused and refer to it. I think there is no use keeping it around (who still uses batteries 1?) and removing it would remove the source of mistakes.

**Comment by gasche** [comment]
That's a good idea. Would someone more interested in web stuff than I am suggest the proper way to handle this? I could just delete the files, or make `hdoc` a copy/symlink of `hdoc2`, which would silently redirect users to the new documentation. Is it desirable? Or should we add some kind of explicit redirection page? Who is volunteering to write the HTML code of this rediction page?

**Comment by c-cube** [comment]
I think if you remove (as in, delete) the old documentation, google will quickly stop referencing it. It might be possible to propose a tarball of the doc, juste in case, but I think the URL for `batteries v1` should explicitely disappear.

**Comment by gasche** [comment]
Thanks, I just did this.
