### ISSUE TITLE
Infix operators (--) and (---) don't work for Big_int

### ISSUE THREAD

**Issue by 314eter** [ocaml-batteries-team/batteries-included#674]
The bug is introduced in commit 3129fbbac0a7888d9ff53b5673ee61d99547e200. The module `MakeInfix`

```ocaml
module MakeInfix (Base : NUMERIC_BASE) :
  Infix with type bat__infix_t = Base.t = struct

  type bat__infix_t = Base.t
  let ( + ), ( - ), ( * ), ( / ), ( ** ) = Base.add, Base.sub, Base.mul, Base.div, Base.pow
  let ( -- )  x y = BatEnum.seq x Base.succ ( (>=) y )
  let ( --- ) x y =
    if y >= x then x -- y
    else BatEnum.seq x Base.pred ((<=) y)
end
```

uses comparisons `(>=)` and `(<=)` which are not yet defined by `MakeCompare`.

**Comment by gasche** [comment]
Thanks for the report! Notifying @rixed in case he would want to look at it. I'll be having a look, but maybe not today.

**Comment by rixed** [comment]
I should be able to have a look at this this evening, thank you for the notice.
