### ISSUE TITLE
Functorized maps don't have `union`

### ISSUE THREAD

**Issue by leafac** [ocaml-batteries-team/batteries-included#680]
Polymorphic maps have `union` and functorized maps don't. I tripped over this and lost an hour today.

Is there a reason for it or can we fix this?

**Comment by gasche** [comment]
You can workaround the lack of `union` by using `merge` instead, which can easily express `union`.

I think that the lack of functorized union was just a historic omission (the functorized code started from the stdlib interface which did not have `union`, while the polymorphic code started from the extlib interface which did have it, and apparently they have never been unified).

In retrospect, not having added this function is a very good thing, given that the standard library added a functorized map in 4.03 with an incompatible type (it takes a `('a -> 'a -> 'a option)` argument, doing a bit of merge's job at the same time). This means that we have to provide this richer interface in Batteries, even if it is not completely consistent with the polymorphic case. (I think `union` is a bad name for this function, but I guess it's partly my responsibility for not complaining to the stdlib developers when this function was added.)

**Comment by leafac** [comment]
> You can workaround the lack of union by using merge instead, which can easily
> express union.

I'm sorry, you say it "can easily be done", but I don't see how. Would care to
elaborate? My version is the following:

```
let var_map_union m2 m1 =
  Var_map.fold Var_map.add m2 m1
;;
```

I couldn't test it yet, but I think it works. Also, it is a one-liner, so I'm
comfortable leaving this in. Nevertheless, I'd be interested in knowing how to
use `merge` to do it.

> I think that the lack of functorized union was just a historic omission (the
> functorized code started from the stdlib interface which did not have union,
> while the polymorphic code started from the extlib interface which did have it,
> and apparently they have never been unified).

It's nice to have some perspective, thanks for sharing.

> In retrospect, not having added this function is a very good thing, given that
> the standard library added a functorized map in 4.03 with an incompatible type
> (it takes a ('a -> 'a -> 'a option) argument, doing a bit of merge's job at the
> same time). This means that we have to provide this richer interface in
> Batteries, even if it is not completely consistent with the polymorphic case. (I
> think union is a bad name for this function, but I guess it's partly my
> responsibility for not complaining to the stdlib developers when this function
> was added.)

I understand. I think differences between the polymorphic and functorized APIs
for the same functionality are misleading, but I can live with that. For the
moment, I'll close this issue report, as there appears to be issue, just
expected behavior, after all.

Thanks a lot for the clarification.

**Comment by gasche** [comment]
I reopened: I'm using your issue to track the fact that we need to add stdlib's `union` function. (There are knobs in place in Batteries to make sure we don't forget to include new stdlib functions, and I don't know why they failed here). Thank you very much, by the way, for making me (indirectly) notice this.

The interface of `merge` is as follows:

```ocaml
  val merge:
    (key -> 'a option -> 'b option -> 'c option) -> 'a t -> 'b t -> 'c t
  (** [merge f m1 m2] computes a map whose keys is a subset of keys of [m1]
      and of [m2]. The presence of each such binding, and the corresponding
      value, is determined with the function [f].
  *)
```

The merge function `key -> 'a option -> 'b option -> 'c option` will be called on each key that is present in one or the other map, passing `None` when the key is absent. This means that whenever both arguments are `Some _`, the key is present on both sides. So you can implement union with:

```
let union m1 m2 =
  let join k v1 v2 =
    match v1, v2 with
    | Some _, Some _ -> v2 (* prefer m2's values over m1's *)
    | None, _ | _, None -> None
  in merge join m1 m2
```

This could be noticeably more efficient that your implementation in some case (in particular, `merge` will always choose the map will the least bindings to iterate on).

**Comment by leafac** [comment]
> I reopened: I'm using your issue to track the fact that we need to add
> stdlib's `union` function.

Fair enough :smile:

> (There are knobs in place in Batteries to make sure we don't forget to include
> new stdlib functions, and I don't know why they failed here). Thank you very
> much, by the way, for making me (indirectly) notice this.

It's my pleasure to be of any help.

> The interface of `merge` is as follows:
>
> ```ocaml
> val merge:
>   (key -> 'a option -> 'b option -> 'c option) -> 'a t -> 'b t -> 'c t
> (** [merge f m1 m2] computes a map whose keys is a subset of keys of [m1]
>     and of [m2]. The presence of each such binding, and the corresponding
>     value, is determined with the function [f].
> *)
> ```
>
> The merge function `key -> 'a option -> 'b option -> 'c` option will be called
> on each key that is present in one or the other map, passing `None` when the key
> is absent. This means that whenever both arguments are `Some _`, the key is
> present on both sides. So you can implement union with:
>
> ```ocaml
> let union m1 m2 =
>   let join k v1 v2 =
>     match v1, v2 with
>     | Some _, Some _ -> v2 (* prefer m2's values over m1's *)
>     | None, _ | _, None -> None
>   in merge join m1 m2
> ```

I don't think I understand your implementation correctly:

1. Shouldn't `join` return an option? The type signature reads `(... -> 'c
   option) ...`. I.e., shouldn't the first branch of the `match` clause be:

   ```ocaml
   | Some _, Some _ -> Some v2 (* prefer m2's values over m1's *)
   ```

2. Suppose `v1` is `None`, but `v2` is `Some thing`. The resulting map should
   still have the key with `thing` in it. So shouldn't the second branch of the
   `match` clause be:

   ```ocaml
   | None, Some thing | Some thing, None -> Some thing
   | None, None -> None
   ```

I hope you don't find these questions annoying, I'm trying to get my head
straight on the details.

> This could be noticeably more efficient that your implementation in some case
> (in particular, `merge` will always choose the map will the least bindings to
> iterate on).

That's interesting to know, thanks for the information. Performance isn't a
concern, because I'm dealing with small-enough maps. But I'm definitely keeping
that in mind for the future.

-----

Thanks a lot for the help and thanks for maintaining Batteries, which is a
life-saver in OCaml :+1:

**Comment by gasche** [comment]
In my code above, `v1` and `v2` are options, so returning one of them returns an option. Your point 2 is completely correct, though: I was implementing `inter` instead of `union`. Sorry! One should rather write something like

```ocaml
let union m1 m2 =
  let join k opt1 opt2 =
    match opt1, opt2 with
    | None, None -> None
    | _, Some _ -> opt2 (* prefers second value when both are present *)
    | Some _ , _ -> opt1
  in merge join m1 m2
```

Note: that `_, Some _ -> opt2` is equivalent to `_, Some v2 -> Some v2`, but more efficient in some implementations (the naive interpretation of the second version re-allocates a `Some ...` block instead of reusing an existing one). In general it's better to optimize for clarity, so do pick whichever you find more readable, but in a standard library it is sometimes worth making sure code is as efficient as it reasonably can, as we don't know how users use it and whether it will end up in their performance-critical code or not.

**Comment by leafac** [comment]
I understand the example now. And I agree that Batteries—being a library—needs to make different choices regarding readability vs. performance trade-offs than I'd make in my application.

I appreciate the careful explanations and the assistance. Thank you very much. And thanks again for maintaining Batteries.

**Comment by UnixJunkie** [comment]
@leafac patch welcome if you want to move this forward

**Comment by leafac** [comment]
@UnixJunkie: I’m sorry but I’m not in a position to contribute with a patch. I’m not familiar enough with Batteries’ code base.

**Comment by leafac** [comment]
I’m closing this since so much time has passed…
