### ISSUE TITLE
`make test` fails with `Unbound module QuickCheck`

### ISSUE THREAD

**Issue by thizanne** [ocaml-batteries-team/batteries-included#698]
On a fresh clone. 

Possibly relevant installed opam packages: 

```
$ opam show quickcheck qcheck qtest ounit benchmark | egrep "package| version"
             package: benchmark
             version: 1.4
             package: ounit
             version: 2.0.0
             package: qcheck
             version: 0.4
             package: qtest
             version: 2.1.1
             package: quickcheck
             version: 1.0.2
```

**Comment by c-cube** [comment]
This is likely because you have an old `qcheck` AND an old `qtest` (there is a conflict between them, which I intend to remove soon by re-splitting qcheck and qtest apart, yay). Try removing `qcheck` and upgrading `qtest`?

**Comment by thizanne** [comment]
Removing `qcheck` made it work, and upgrading `qtest` had no impact (it reinstalled the same version). For the record, reinstalling `qcheck` made the test fail again.

**Comment by c-cube** [comment]
Thanks! This will be solved soon, hopefully, as `qtest` will depend on `qcheck` (with proper version bounds) so this kind of confusion will go away.
