### ISSUE TITLE
BatteriesConcreteQueue cmi and cmx

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-batteries-team/batteries-included#701]
are installed capitalized while the rest is consistently installed uncapitalized. 

See https://github.com/ocaml-batteries-team/batteries-included/commit/9167661701e15587e6649eabb51ae39e897bfce8#diff-2d8a8d7d55d223fe187efdf03f6ca050R124

**Comment by UnixJunkie** [comment]
fix in https://github.com/ocaml-batteries-team/batteries-included/pull/741
