### ISSUE TITLE
no BatList.shuffle

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#702]
no Array.shuffle too.

**Comment by UnixJunkie** [comment]
How about this one:

    let shuffle (rand_state: Random.State.t option) (l: 'a list) =
      let () = match rand_state with
        | Some s -> Random.set_state s
        | None -> Random.self_init ()
      in
      let with_rands =
        List.map (fun i ->
            let rand = Random.bits () in
            (rand, i)
          ) l
      in
      let shuffled =
        List.sort (fun (rand0, _i) (rand1, _j) ->
            compare rand0 rand1
          ) with_rands
      in
      List.map snd shuffled

**Comment by c-cube** [comment]
I'd suggest to write `Array.shuffle` first, then use it for shuffling lists. You can take code from https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCArray.ml#L271 if you want :-)

**Comment by UnixJunkie** [comment]
I was thinking about that since List.sort dumps the list into an array if I'm right.

**Comment by gasche** [comment]
To be clear, we do have a shuffle implementation, it's in the `BatRandom` module. (It's `enum -> 'a array` but internally operates on arrays, as it should)

**Comment by UnixJunkie** [comment]
proposal here: https://github.com/ocaml-batteries-team/batteries-included/pull/707

**Comment by UnixJunkie** [comment]
Any comments? @thizanne maybe?

**Comment by UnixJunkie** [comment]
What can I do for this to go further?

**Comment by gasche** [comment]
I cannot find time to look at the PR before the week-end. I hope give some cycles to Batteries at the beginning of next week.

**Comment by UnixJunkie** [comment]
corresponding pull request was merged recently
