### ISSUE TITLE
BatResult does not have a map function

### ISSUE THREAD

**Issue by ifazk** [ocaml-batteries-team/batteries-included#704]
I know that BatResult exports a `map_default` function, but I was looking for something similar to the `map` in BatOption. Is there any particular reason why something similar to the flowing is missing from BatResult.ml?

    let map f = function
      | Bad e -> Bad e
      | Ok v  -> Ok (f v)

If there isn't any particular reason, could we have this added?

**Comment by gasche** [comment]
Yes, you could add this. I think a `map_both` that would also take a map for the `Bad` payload would also be nice. Please include tests as well (see BatOption.ml for examples of use of inline tests).

**Comment by ifazk** [comment]
Ok. I will send a PR once I'm done.
