### ISSUE TITLE
no documentation showing in ocp-browser

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#706]
Hi, even if I press space, there is no ocamldoc showing inside of ocp-browser.
Maybe it is packaging-related: the ocamldoc is not installed (or some other files).
How to make it work?

**Comment by UnixJunkie** [comment]
It works for @c-cube 's containers (and the stdlib).

**Comment by c-cube** [comment]
You need to check whether `.cmt{,i}` files are installed.

**Comment by whirm** [comment]
The same is happening to me: no `.cmt{,i}` files are present (installing via opam).

**Comment by UnixJunkie** [comment]
this would be cool to correct this before next minor release

**Comment by UnixJunkie** [comment]
@c-cube no .cmt{i} files are installed for batteries by the opam package :(

**Comment by UnixJunkie** [comment]
At least we have .cmi files installed so batteries will be indexed by the real Hoogle for OCaml.
https://github.com/ndmitchell/hoogle/issues/203

**Comment by UnixJunkie** [comment]
done by #740
