### ISSUE TITLE
we should have ready to use IntSet, StringSet, etc.

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#709]
Hello,
This was recently asked by someone else.
Since we are 'batteries included', I think we should provide
already made sets.
This was a good idea.

**Comment by UnixJunkie** [comment]
could avoid the stupid code like this


    module IntSet = struct
      include Set.Make(Int)
      (* extend type with more operations *)
      let of_list = L.fold_left (fun acc x -> add x acc) empty
      let to_list = elements
    end

**Comment by UnixJunkie** [comment]
It could avoid stupid code like this in one's project:

    module IntSet = struct
      include Set.Make(Int)
      (* extend type with more operations *)
      let of_list = L.fold_left (fun acc x -> add x acc) empty
      let to_list = elements
    end

**Comment by UnixJunkie** [comment]
Apparently there is something to do when addind a new module in batteries.
Is there some myocamlbuild.ml or _tags file I should update?
I am trying to add src/batIntSet.ml for example.

**Comment by thizanne** [comment]
Shouldn't `IntSet` be in `batSet.ml` ? `Set` would then provide polymorphic sets (`Set` module), a functor (`Set.Make`), and some common applications of the functor (`Set.IntSet` and so on).

**Comment by UnixJunkie** [comment]
I would prefer to write IntSet directly: Set.IntSet is redundant.
Syntax is important and conciseness too to have beautiful code.

**Comment by thizanne** [comment]
Then what about something like `Set.Int` (or `Int.Set`, again ?) ? Conciseness is cool but I don't think `IntSet` should be seen as a totally separated module from the `Int` and `Set` ones.

**Comment by c-cube** [comment]
I think `Set.Int` (and `Map.String`) makes the most sense.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/pull/711

**Comment by UnixJunkie** [comment]
done by ffac0420a5e4b83239c3213547ed711acf0e2621
