### ISSUE TITLE
metaocaml conflict

### ISSUE THREAD

**Issue by nilsbecker** [ocaml-batteries-team/batteries-included#710]
In BatSet there is `val (>.) : t -> t -> bool  (** strict superset *)`. I tried to compile batteries with the newest MetaOCaml and it complains at this position, most likely since this value conflicts with MetaOCaml's quotation syntax. They won't change that according to Oleg - could Batteries step out of the way by renaming these infix operators?

**Comment by thizanne** [comment]
Although I don't use it (yet), I think that being compatible with MetaOcaml is a valid concern. This could be another (easy) change to add for the next major release.

**Comment by gasche** [comment]
We try to maintain a `v3` branch with incompatible changes, feel free to send a PR against this.

**Comment by UnixJunkie** [comment]
Go for it @thizanne \(^v^)/

**Comment by gasche** [comment]
(I just rebased the `v3` branch on top of the current master. We should remember to do this from time to time.)

**Comment by rixed** [comment]
Someone should learn how to use a ticket tracker: https://github.com/ocaml-batteries-team/batteries-included/issues/908 :)

Therefore closing this one as well.
