### ISSUE TITLE
we don't have a mktempdir?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#713]
that would be handy to me

**Comment by vogler** [comment]
There's https://caml.inria.fr/pub/docs/manual-ocaml/libref/Filename.html#VALtemp_file which takes a prefix.

**Comment by UnixJunkie** [comment]
It doesn't create any temp dir ...

**Comment by UnixJunkie** [comment]
Since we have Unix.mkdir, I propose to add Unix.mk_temp_dir.

**Comment by UnixJunkie** [comment]
not many votes, no PR
