### ISSUE TITLE
request for feature: with_temp_outfile

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#717]
I think we have something like with_in_file and with_out_file.
Would be cool to have a with_out_file where the out_file is transient: i.e. after the function
returns this out_file is removed.
But during the function execution we knew what this out_file filename was.
I might come up with some scratch/prototype code soon.

**Comment by UnixJunkie** [comment]
Looks like the thing I need:

    let with_out_file (fn: string) (f: out_channel -> 'a): 'a =
      let output = open_out fn in
      let res = f output in
      close_out output;
      res
    
    let with_temp_out_file (f: out_channel -> 'a): 'a =
      let temp_file = Filename.temp_file "" (* no_prefix *) "" (* no_suffix *) in
      let res = with_out_file temp_file f in
      Sys.remove temp_file;
      res

**Comment by UnixJunkie** [comment]
In fact that's enough

    let with_temp_out_file (f: string -> 'a): 'a =
      let temp_file = Filename.temp_file "" (* no_prefix *) "" (* no_suffix *) in
      let res = f temp_file in
      Sys.remove temp_file;
      res

**Comment by UnixJunkie** [comment]
I let other mainteiners judge if this is a useful enough addition to batteries

**Comment by c-cube** [comment]
You need to protect against exceptions in `f`.

**Comment by UnixJunkie** [comment]
nice catch

**Comment by UnixJunkie** [comment]
but the then the return type is 'a option

**Comment by UnixJunkie** [comment]
what is your proposition Simon? In terms of whole type signature and code.

**Comment by c-cube** [comment]
I'm on my phone, but I just suggest to try/with to remove the resource whatever happens (re-raising any exception). Same as with_* in batteries and containers, in general, I think.
-- 
Simon

**Comment by UnixJunkie** [comment]
not many votes
