### ISSUE TITLE
feature request: BatMap.union and BatMap.intersect

### ISSUE THREAD

**Issue by jrochel** [ocaml-batteries-team/batteries-included#719]
See https://github.com/ocaml-batteries-team/batteries-included/pull/703.
I'd be happy to supply a patch if there is anyone who would actually pull it.

**Comment by UnixJunkie** [comment]
Isn't what you are looking for included in the stdlib?
Map.merge / Map.union.

**Comment by UnixJunkie** [comment]
Batteries is an overlay to the stdlib so we also have those.

**Comment by jrochel** [comment]
`BatMap.Make` does not have a `union` function. Is it intentional or did just someone forget to re-export it? In any case, is there interest in functions like `unions`, `unions_by`, `of_list` etc from my pull request?
I might sound like I need guidance with this which is not the case. I'm just trying to get a feel on how open the batteries community is for extensions before doing the actual work.

**Comment by UnixJunkie** [comment]
Yes, you are right.
I guess Map.union and Map.merge are recent additions to the stdlib not yet reflected into batteries.
Please send a separate pull request for each of them (with tests).
It is very likely that your pull requests will be accepted.
Pull requests are easier to review (and hence reviewed faster) if they treat a single problem at a time.

**Comment by jrochel** [comment]
Alright, I'll do it this way then. Thanks for your feedback! I suppose I will get around to do this in a few weeks.
