### ISSUE TITLE
We miss Map.find_with_default def k m

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#723]
Returns the default value instead of throwing an exception in the Not_found case.
That allows for simpler code.

**Comment by thizanne** [comment]
`Map.find k m |? def` is shorter than `Map.find_with_default def k m` if you `open BatteriesExceptionless`, but I agree that sometimes you want the exception-raising functions.

**Comment by UnixJunkie** [comment]
done by https://github.com/ocaml-batteries-team/batteries-included/pull/730
