### ISSUE TITLE
strange type signature of BatList.reduce

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#725]
val BatList.reduce ('a -> 'a -> 'a) -> 'a list -> 'a
shouldn't it be:
val BatList.reduce ('a -> 'a -> 'b) -> 'a list -> 'b

**Comment by thizanne** [comment]
No it shouldn't: think of `reduce` as `fold` but using the first (or last) element for initialising the accumulation.
