### ISSUE TITLE
we need a BatFile.all_lines

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#735]
This is just too ugly and inefficient:
BatList.of_enum (BatFile.lines_of input_fn)

**Comment by UnixJunkie** [comment]
should we name it get_all_lines?
Any better name?

    val BatFile.get_lines: string -> string list

**Comment by UnixJunkie** [comment]
We need a pair of functions in fact:
like BatFile.read_lines_strict and BatFile.write_lines_strict
strict meaning we don't want an enum in there

**Comment by c-cube** [comment]
This should be more compositional, imho. In containers:

```ocaml
CCIO.with_in "some_file" CCIO.read_lines_l
```

where `read_lines_l : in_channel -> string list` and `with_in : string -> (in_channel -> 'a) -> 'a`.

**Comment by UnixJunkie** [comment]
I am thinking about the following two functions for BatList:

    let of_file in_chan =
      let res, exn = unfold_exc (fun () -> input_line in_chan) in
      if exn = End_of_file then res
      else raise exn

    let to_file ~newline lines out_chan =
      List.iter (fun line ->
          Printf.printf out_chan "%s%s" line ~newline
        ) lines

**Comment by UnixJunkie** [comment]
In my utils toolbox, I have: iter_on_lines_of_file, map_on_lines_of_file and the variants with a predicate (only work on lines satisfying the predicate); if people find them useful, I could add them

**Comment by UnixJunkie** [comment]
Not enough voters.
