### ISSUE TITLE
Why is BatList.kahan_sum not the default BatList.fsum?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#736]
Sorry for the maybe stupid question.
Same question for BatArray.kahan_sum?

**Comment by gasche** [comment]
It is noticeably slower -- if I remember correctly I gave some performance number when it was implemented, you may find them in the discussion somewhere. We need to have an explicit `kahan_sum` version anyway, for people that want to make sure they know which algorithm is used and its precision properties.

**Comment by UnixJunkie** [comment]
Ok, fair enough.
