### ISSUE TITLE
Make sets display elements in toplevel

### ISSUE THREAD

**Issue by mars0i** [ocaml-batteries-team/batteries-included#750]
Unlike many common data structures, `Set` sets don't show their contents when evaluated in a toplevel.  Instead, all that's displayed is `- : int mappable = <abstr>`, even after `open Batteries.Set`.   One has to use `elements` to show the contents.  This makes it inconvenient to experiment in a toplevel with data structures that include sets.  (Please forgive my ignorance if I simply don't understand what has to be `open`ed in order to display sets' contents.)

Obviously, for large sets, display of the contents should be truncated with "...", as it is, for example, with large lists.

**Comment by thizanne** [comment]
We should indeed install some printers of our data structures. I think it will be easier to do so when `IO` is fixed in the next major release.

**Comment by mars0i** [comment]
Great--thanks very much.  (And thanks to everyone working on Batteries.  Although I think Jane Street deserves a lot of appreciation and respect for Core.Std, I feel they made some quirky decisions about a few things; Batteries makes more sense to me.)
