### ISSUE TITLE
BatList suggests first and last should raise Empty_list

### ISSUE THREAD

**Issue by rixed** [ocaml-batteries-team/batteries-included#754]
But `first` is actually raising Failure and `last` Invalid_argument.

Empty_list is raised by LazyList and RefList though.
I guess we should catch Failure/Invalid_argument and re-raise Empty_list in `first` and `last`.

**Comment by gasche** [comment]
I don't think it is safe to change the exception raised by a function, even if there is a mismatch with the documentation: the implementation is what people are likely to have tested against.

**Comment by rixed** [comment]
Indeed. Let's clean this next time the major version number is increased, then?

**Comment by thizanne** [comment]
Should we fix the documentation though ?

**Comment by gasche** [comment]
Yes, I think that fixing the documentation (now) would be reasonable.
