### ISSUE TITLE
batteries' code is not compatible with latest release of qcheck (0.6)

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#756]
you have to downgrade qcheck with opam (previous release) in order to pass 'make test'

    opam install qcheck.0.5.3.1

**Comment by c-cube** [comment]
Sorry about the breakage. It's actually possible to modify the code for cheap (old `fun1` and `fun2` functions were renamed, not removed), or use the better new function generators.
