### ISSUE TITLE
Should we have a function to copy files ?

### ISSUE THREAD

**Issue by thizanne** [ocaml-batteries-team/batteries-included#758]
It seems none of `Unix`, `File` and `Sys` modules have a function to copy a file in the file system. We do have ` IO.copy` that does the job, however one need to open the files first, and permissions are not copied.

I'm not sure why we don't have this function (maybe it's for an actual reason), in what module it should be added and what it should exactly do (especially for permissions, is there a portable way to do it properly ?), please discuss.

**Comment by gasche** [comment]
"Portable" hopefully means "on Unixes as well as Windows", and there I don't think there is a pure-OCaml way to do it. We could implement it in C by having ifdefs to use the proper system APIs on both system, but this is not something that Batteries has tried to get into in the past, it sounds like a lot of work to maintain and difficult (there is a highly non-trivial [GPR#1200](https://github.com/ocaml/ocaml/pull/1200/) being reviewed on ocaml/ocaml right now to handle Windows filenames right), I'm not sure that is a wise battle to pick.

**Comment by UnixJunkie** [comment]
there is the fileutils library to do such things

**Comment by UnixJunkie** [comment]
FileUtil.cp should allow you to do what you want.

**Comment by thizanne** [comment]
Fair enough. However we do have things like `rename`, are they simpler to make work on Windows or is it a non-portable function from the past when someone needed a quick-and-dirty one ?

**Comment by UnixJunkie** [comment]
We also have unlink; which is like rm in bash.

**Comment by gasche** [comment]
I think that the functions that don't need to worry about permissions are indeed simpler. (And then the compiler historically added the functions that it really needed for its own runtime, dealing with the arising complexity, and it does not need a permission-preserving function.)

**Comment by thizanne** [comment]
Closing it then. Thanks for advice.

**Comment by UnixJunkie** [comment]
We also have unlink; which is like rm in bash.
