### ISSUE TITLE
Bug: off-by-one in BatVect.insert

### ISSUE THREAD

**Issue by theindigamer** [ocaml-batteries-team/batteries-included#766]
Minimal example:

```
module V = BatVect;;
let a = V.of_list [0;1;2;3];;
V.get a 2 = 2;;
- : bool = true
V.(to_list @@ insert 3 (singleton 10) a);;
- : int list = [0; 1; 2; 10; 3]
```
According to the [documentation](https://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatVect.html), it should be inserted between indices 3 and 4, not 2 and 3.

**Comment by gasche** [comment]
Thanks for the report! After investigating the issue and writing a few test casts, my intuition is that the implementation is correct and the bug is in the specification, so I propose to fix the documentation in #767.
