### ISSUE TITLE
should we do a new minor release

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#781]
If so, please point out outstanding issues or pull requests that need to be closed before.

**Comment by gasche** [comment]
I would like to merge #779 before the new minor release, so that the functions made available for 4.05 support are also available on older releases (as was the norm for previous Batteries+OCaml releases).

**Comment by gasche** [comment]
Note that #779 is ready to merge as far as I am concerned, I was leaving it open in case someone may want to do a review.

**Comment by UnixJunkie** [comment]
OK, I'll start tomorrow, it's the end of the day here and I'm tired.

**Comment by UnixJunkie** [comment]
Can someone run make test on a 32 bits machine using the master branch?
I don't have one under the hand, it will take me some time if I need to create a special VM.

**Comment by UnixJunkie** [comment]
we should only rely on the stable core of qtest / qcheck, or use a system (preprocessor?) to disable some tests when the version of qcheck doesn't support them

**Comment by UnixJunkie** [comment]
For example: Q.Observable and Gen are not supported by older qtest versions; those tests should only be enabled when the qtest version being used supports them

**Comment by UnixJunkie** [comment]
apart from this, tests are OK with ocaml 3.12.1

**Comment by UnixJunkie** [comment]
tests are also OK with ocaml 4.05.0 on a 64bits machine

**Comment by UnixJunkie** [comment]
test_install is also OK

**Comment by UnixJunkie** [comment]
I am testing on i386 (in a VM) with 4.05.0 and apparently Thread.create never succeeds in there ...

**Comment by UnixJunkie** [comment]
Should I be worried (tested with ocaml 4.05.0 and 4.01.0 in an i386 VM):
ocp-browser -> Unix.Unix_error(Unix.EAGAIN, "launch_thread","")
utop -> launch_thread: Resource temporaritly unavailable
Sys_error("Thread.create: Resource temporarily unavailable") in src/batRMutex.ml:128

**Comment by tchajed** [comment]
I'm a little surprised given that there are only 30 threads. However, it's expected that at some point you run out of resources (eg, virtual memory or threads per process) and `pthread_create` fails with `EAGAIN`; see https://stackoverflow.com/questions/8634736/pthread-create-and-eagain.

Can you try changing the last line of the test to  `assert_equal (20*30) (test 20 30) ~printer:string_of_int` (20 threads)? If that works we can just reduce the size of the test.

Could you also report the output of `cat /proc/sys/kernel/threads-max`? On a physical Linux box I get a fairly large number (192761) whereas my 64-bit VM only reports 31570.

**Comment by gasche** [comment]
Given that we don't want to delay the release too much, and that we are reasonably confident that the code changes since the last release should not affect 32bit too much, I think it would be ok to go ahead without 32bit testing.

I've been thinking of setting up Travis CI testing for batteries, maybe we could get a 32bit machine there.

**Comment by gasche** [comment]
I proposed a release summary in #782. I can also do the "release marking" parts of [howto/release](../tree/master/howto/release.md) if that helps, let me know.

**Comment by UnixJunkie** [comment]
My VM was probably nearly out of disk space and that's why creating many threads was failing.
I'm all done with the quality checking then.

**Comment by UnixJunkie** [comment]
If everybody is OK with what is in master, I will create and push the v2.7.0 tag.

**Comment by gasche** [comment]
Fine with me! Will you also send the opam-repository PR and caml-list announce?

**Comment by UnixJunkie** [comment]
opam I can do (and we have to wait for it to be accepted before the announce)

**Comment by UnixJunkie** [comment]
CI tests are running https://github.com/ocaml/opam-repository/pull/10097

**Comment by UnixJunkie** [comment]
done

**Comment by gasche** [comment]
https://github.com/ocaml-batteries-team/batteries-included/releases only contains 2.5.2 as the last release. I will use the "draft a new release" button to have 2.6.0 and 2.7.0 releases visible (I just copy the Changelog as release note).

**Comment by gasche** [comment]
I uploaded the docs. Should I also send the caml-list email, or are you taking care of it?

**Comment by UnixJunkie** [comment]
You can do it or I'll do it tomorrow.
