### ISSUE TITLE
I would need a Buffer.get_lines

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#786]
val get_lines: Buffer.t -> string -> string list

the second parameter is the line separator that was used when filling the buffer

**Comment by gasche** [comment]
Currently we have to do `buf |> BatBuffer.contents |> BatIO.input_string |> BatIO.lines_of`.

**Comment by gasche** [comment]
If you want delimiter support, well `BatBuffer.contents buf |> BatString.nsplit ~by:"\n"`.
