### ISSUE TITLE
BatString.split_on_char

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#787]
should have an ignore trailing separator optional argument defaulting to false

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/issues/786

**Comment by UnixJunkie** [comment]
maybe an ignore leading separator too

**Comment by UnixJunkie** [comment]
Comments from other maintainers would be welcome.
We can close this if judged useless.
I can implement it if judged useful (I need this when writing parsers for chemistry file formats).

**Comment by gasche** [comment]
Sorry for the lack of feedback. I'm a bit reluctant at the idea of changing the signature of a function that exists in the standard library -- for example that would require a special-case in the "compatibility tests" (that check that we implement the same signature), and it's not such a good practice.

**Comment by UnixJunkie** [comment]
OK, no problem.
