### ISSUE TITLE
count number of times char is found in string

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#791]
We also miss that one.

**Comment by c-cube** [comment]
Sounds like efficient iterators would make this easy.

**Comment by UnixJunkie** [comment]
cf. https://github.com/ocaml-batteries-team/batteries-included/pull/798

**Comment by UnixJunkie** [comment]
we need a since NEXT_RELEASE if this is accepted

**Comment by UnixJunkie** [comment]
PR was merged
