### ISSUE TITLE
BatString.starts_with is too slow

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#792]
this might be faster

    let starts_with s prfx =
      let len_s = String.length s in
      let len_p = String.length prfx in
      if len_s < len_p then
        false
      else
        let sub = String.sub s 0 len_p in
        String.equal prfx sub

**Comment by c-cube** [comment]
Your proposal allocates a whole sub-string. In containers I have the following:

```ocaml
let prefix ~pre s =
  String.length pre <= String.length s &&
  begin
    let i = ref 0 in
    while !i < String.length pre && s.[!i] = pre.[!i] do incr i done;
    !i = String.length pre
  end
```

**Comment by UnixJunkie** [comment]
I knew some clever people would propose something even better. :)

**Comment by UnixJunkie** [comment]
according to my tests https://gist.github.com/UnixJunkie/9bf2100b471daafa631ba56634c3a939
Containers.String.prefix is about 8% faster than Batteries.starts_with.
I vote for shamelessly using Simon's code.

**Comment by UnixJunkie** [comment]
./test 
batteries: 1.051806s
containers: 0.948760s
./test 
batteries: 1.048601s
containers: 0.963531s
./test 
batteries: 1.052694s
containers: 0.961742s

**Comment by UnixJunkie** [comment]
I should have a more statistically robust benchmark ...

**Comment by UnixJunkie** [comment]
I did some more serious benchmarking here: https://github.com/UnixJunkie/string_starts_with_bench.
Apparently, the one currently in batteries is faster than the one from Containers.

**Comment by c-cube** [comment]
After looking at the benchmarks, and batteries' current code (which uses `BatReturn` + for loop), I came up with the following:

```ocaml
exception Exit_false

let prefix_loop ~pre s =
  String.length pre <= String.length s &&
  try
    for i=0 to String.length pre-1 do
      if String.unsafe_get s i != String.unsafe_get pre i
      then raise Exit_false
    done;
    true
  with Exit_false -> false
```

my modified benchmarks give the following (with 4.04.0+flambda and using `benchmark` instead of `bench`, and where `containers_loop` is the function above)

```
Throughputs for "batteries", "containers", "containers_unsafe", "containers_pure", "containers_for" each running for at least 3 CPU seconds:
        batteries:  3.18 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 730.06/s (n=2312)
       containers:  3.15 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 321.38/s (n=1010)
containers_unsafe:  3.14 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 351.40/s (n=1101)
  containers_pure:  3.16 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 472.43/s (n=1488)
   containers_for:  3.16 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 819.83/s (n=2585)
                   Rate containers containers_unsafe containers_pure batteries containers_for
       containers 321/s         --               -9%            -32%      -56%           -61%
containers_unsafe 351/s         9%                --            -26%      -52%           -57%
  containers_pure 472/s        47%               34%              --      -35%           -42%
        batteries 730/s       127%              108%             55%        --           -11%
   containers_for 820/s       155%              133%             74%       12%             --
```

**Comment by gasche** [comment]
Note that the Batteries master does not use `Return` or local exception anymore, as they are too slow on Javascript backends. Here is a link to the [current implementation](https://github.com/ocaml-batteries-team/batteries-included/blob/master/src/batString.mlv#L45-L63); would you be willing to add it to your benchmark?

**Comment by UnixJunkie** [comment]
I think the old version (with BatReturn and an exception) was slower than container's one, not the current one in the master of batteries.

**Comment by UnixJunkie** [comment]
@c-cube if you have a link to your benchmarking code, I'd like to see it. So that I can also use benchmark in the future, if it fits better to me than bench.

**Comment by c-cube** [comment]
I moved the benchmarks into containers (and updated my own prefix/suffix versions). At containers ff469211afe8da9c898e40e365d1584925c10949 , there is a "run_benchs" binary with the tests. If the dependencies are all installed, and the proper `--enable` flags passed, it builds. One can run the benchmarks with `./run_benchs.native -p string.prefix`. I get the following results (where `bat_prefix` is the code linked by @gasche above and `sub_eq` is the initial proposal by @UnixJunkie with `String.sub`):

```
*** Run benchmarks for path "string.prefix.max_len:1000,max_pre_len:100.100"

Throughputs for "containers", "while_unsafe", "loop_unsafe", "for_unsafe", "sub_eq", "bat_prefix" each running for at least 3 CPU seconds:
  containers:  3.20 WALL ( 3.19 usr +  0.00 sys =  3.19 CPU) @ 247351.11/s (n=789240)
while_unsafe:  3.19 WALL ( 3.18 usr +  0.00 sys =  3.18 CPU) @ 226029.39/s (n=719155)
 loop_unsafe:  3.14 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 308069.11/s (n=964943)
  for_unsafe:  3.16 WALL ( 3.14 usr +  0.01 sys =  3.14 CPU) @ 248371.24/s (n=780908)
      sub_eq:  3.18 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 434609.85/s (n=1375578)
  bat_prefix:  3.16 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 324264.35/s (n=1022209)
                 Rate while_unsafe containers for_unsafe loop_unsafe bat_prefix sub_eq
while_unsafe 226029/s           --        -9%        -9%        -27%       -30%   -48%
  containers 247351/s           9%         --        -0%        -20%       -24%   -43%
  for_unsafe 248371/s          10%         0%         --        -19%       -23%   -43%
 loop_unsafe 308069/s          36%        25%        24%          --        -5%   -29%
  bat_prefix 324264/s          43%        31%        31%          5%         --   -25%
      sub_eq 434610/s          92%        76%        75%         41%        34%     --
**********************************************************************
*** Run benchmarks for path "string.prefix.max_len:1000,max_pre_len:100.1000"

Throughputs for "containers", "while_unsafe", "loop_unsafe", "for_unsafe", "sub_eq", "bat_prefix" each running for at least 3 CPU seconds:
  containers:  3.05 WALL ( 3.05 usr +  0.00 sys =  3.05 CPU) @ 20942.97/s (n=63818)
while_unsafe:  3.14 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 17522.14/s (n=55085)
 loop_unsafe:  3.15 WALL ( 3.15 usr +  0.00 sys =  3.15 CPU) @ 22640.27/s (n=71281)
  for_unsafe:  3.14 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 20680.15/s (n=64820)
      sub_eq:  3.18 WALL ( 3.18 usr +  0.00 sys =  3.18 CPU) @ 26261.07/s (n=83447)
  bat_prefix:  3.11 WALL ( 3.10 usr +  0.00 sys =  3.10 CPU) @ 24793.16/s (n=76982)
                Rate while_unsafe for_unsafe containers loop_unsafe bat_prefix sub_eq
while_unsafe 17522/s           --       -15%       -16%        -23%       -29%   -33%
  for_unsafe 20680/s          18%         --        -1%         -9%       -17%   -21%
  containers 20943/s          20%         1%         --         -7%       -16%   -20%
 loop_unsafe 22640/s          29%         9%         8%          --        -9%   -14%
  bat_prefix 24793/s          41%        20%        18%         10%         --    -6%
      sub_eq 26261/s          50%        27%        25%         16%         6%     --
**********************************************************************
*** Run benchmarks for path "string.prefix.max_len:1000,max_pre_len:15.100"

Throughputs for "containers", "while_unsafe", "loop_unsafe", "for_unsafe", "sub_eq", "bat_prefix" each running for at least 3 CPU seconds:
  containers:  3.12 WALL ( 3.11 usr +  0.00 sys =  3.11 CPU) @ 395536.73/s (n=1230440)
while_unsafe:  3.11 WALL ( 3.10 usr +  0.00 sys =  3.10 CPU) @ 779249.53/s (n=2416745)
 loop_unsafe:  3.15 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 972220.03/s (n=3052557)
  for_unsafe:  3.19 WALL ( 3.18 usr +  0.00 sys =  3.18 CPU) @ 390641.35/s (n=1242886)
      sub_eq:  3.18 WALL ( 3.17 usr +  0.00 sys =  3.17 CPU) @ 433564.41/s (n=1375735)
  bat_prefix:  3.15 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 803577.09/s (n=2522496)
                 Rate for_unsafe containers sub_eq while_unsafe bat_prefix loop_unsafe
  for_unsafe 390641/s         --        -1%   -10%         -50%       -51%        -60%
  containers 395537/s         1%         --    -9%         -49%       -51%        -59%
      sub_eq 433564/s        11%        10%     --         -44%       -46%        -55%
while_unsafe 779250/s        99%        97%    80%           --        -3%        -20%
  bat_prefix 803577/s       106%       103%    85%           3%         --        -17%
 loop_unsafe 972220/s       149%       146%   124%          25%        21%          --
**********************************************************************
*** Run benchmarks for path "string.prefix.max_len:1000,max_pre_len:15.1000"

Throughputs for "containers", "while_unsafe", "loop_unsafe", "for_unsafe", "sub_eq", "bat_prefix" each running for at least 3 CPU seconds:
  containers:  3.11 WALL ( 3.10 usr +  0.00 sys =  3.10 CPU) @ 30711.15/s (n=95113)
while_unsafe:  3.14 WALL ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 42733.57/s (n=133810)
 loop_unsafe:  3.20 WALL ( 3.19 usr +  0.00 sys =  3.19 CPU) @ 48812.24/s (n=155561)
  for_unsafe:  3.15 WALL ( 3.14 usr +  0.00 sys =  3.14 CPU) @ 30524.21/s (n=95861)
      sub_eq:  3.15 WALL ( 3.14 usr +  0.01 sys =  3.14 CPU) @ 31254.36/s (n=98232)
  bat_prefix:  3.14 WALL ( 3.12 usr +  0.00 sys =  3.13 CPU) @ 51452.69/s (n=160921)
                Rate for_unsafe containers sub_eq while_unsafe loop_unsafe bat_prefix
  for_unsafe 30524/s         --        -1%    -2%         -29%        -37%       -41%
  containers 30711/s         1%         --    -2%         -28%        -37%       -40%
      sub_eq 31254/s         2%         2%     --         -27%        -36%       -39%
while_unsafe 42734/s        40%        39%    37%           --        -12%       -17%
 loop_unsafe 48812/s        60%        59%    56%          14%          --        -5%
  bat_prefix 51453/s        69%        68%    65%          20%          5%         --
./run_benchs.native -p string.prefix  90.00s user 0.04s system 99% cpu 1:30.32 total
```

**Comment by c-cube** [comment]
So apparently the current code in batteries is the best in most cases!

**Comment by gasche** [comment]
The `String.sub` version is actually rather fast (and we could consider that it may become even faster if the stdlib ever decided to use `memcmp` etc.), but it performs an extra allocation which some people may prefer to avoid (usually it doesn't matter). I'm happy with the existing implementation or the newly proposed one, but my time working on Batteries is limited and I'm not sure this is worth extra work for the three of us -- of course it is always fun.

**Comment by c-cube** [comment]
The `String.sub` version seems to be meh when the prefix string is short (the tests with `max_pre_len=15` above). The recursive function in batteries seems good in all cases.

**Comment by gasche** [comment]
And I think we expect most prefixes to be fairly short.

**Comment by c-cube** [comment]
That thread has been productive, I think — it provides more weight to the current implementation in batteries, and helped me improve my own code ;)

**Comment by UnixJunkie** [comment]
The String.sub version uses an external C function (caml_string_equal).
Not sure it will please the js_of_ocaml crowds.
So, finally, I am also OK with the current implementation in batteries.

**Comment by UnixJunkie** [comment]
It's not obvious to me how to read the results of benchmark. What is the bottom line?
What is the fastest method?
I there a manager/tired programmer output mode? :)

**Comment by gasche** [comment]
> and helped me improve my own code ;)

Feel free to reuse the Batteries version if useful, of course. As the author of the new version, I give you my permission to use it with the Containers' license -- I don't remember whether it is the same.

**Comment by c-cube** [comment]
Thanks! Containers is BSD, but anyway I just took the idea of the recursive loop, and the code is small anyway ;)
However the difference in performance is not very intuitive for me to predict; it seems to be only caused by differences over what is closure-captured and what is not.

@UnixJunkie ignore the bottom line, sorry. The rest is a comparison table of the throughput of each function over a given input (the higher, the better), with various parameters about the generated strings/prefixes lengths.
