### ISSUE TITLE
We need a 4.06-ready release

### ISSUE THREAD

**Issue by gasche** [ocaml-batteries-team/batteries-included#803]
We need a 4.06-ready release. I hoped to do one last week (before the actual 4.06 release) but had no time. I'm creating this issue to keep track of the need and report on progress.

I just pushed two commits in trunk that (1) restore compatibility with pre-4.02 OCaml versions ( https://github.com/ocaml-batteries-team/batteries-included/commit/b89b8219348386d1144cb6c8c555546baabf1b24 ) and (2) make it possible to test batteries on these older versions by working-around `qtest` incompatible changes ( https://github.com/ocaml-batteries-team/batteries-included/commit/60ffa0fec2c1b7e245fec532da530a1c0c5ac64b ). 

I have tested that `make tests` passes under both 4.06 and 4.00.1, but I haven't started following the [release instructions](https://github.com/ocaml-batteries-team/batteries-included/blob/master/howto/release.md) yet.

**Comment by UnixJunkie** [comment]
I can help with the release starting from next week

**Comment by gasche** [comment]
I just released 2.8.0.
