### ISSUE TITLE
BatString.cut

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#807]
Like the cut unix command:

    val cut : char -> int -> string -> string = <fun>
    cut ',' 2 "a,b,c";;
    string = "c"

**Comment by UnixJunkie** [comment]
onegai shimasu

**Comment by UnixJunkie** [comment]
the cut command has indexes starting at 1 I think.
However, I don't think we have to follow this convention.

**Comment by thizanne** [comment]
Starting at 0 is coherent with virtually every other OCaml indexing convention. Screw unix.

**Comment by UnixJunkie** [comment]
done by https://github.com/ocaml-batteries-team/batteries-included/pull/856
thanks to @thizanne and @FkHina
