### ISSUE TITLE
MultiPMap.map erronous documentation 

### ISSUE THREAD

**Issue by sapristi** [ocaml-batteries-team/batteries-included#812]
Hello, 
some precisions are missing in the description of the MultiPMap.map documentation.
Namely, it seems that the second parameter has been completely forgotten.

Also the module MultiMap is missing from the modules list at 
[http://ocaml-batteries-team.github.io/batteries-included/hdoc2/](http://ocaml-batteries-team.github.io/batteries-included/hdoc2/), is this on purpose ?

**Comment by UnixJunkie** [comment]
Hello,
A pull request to improve the documentation would be welcome.
Since you are a user of this module, you probably know how it behaves and what the doc should say.
If you even had a look at the doc, then that's even better.
Thanks,
F.

**Comment by sapristi** [comment]
Ok I clarified some points in the doc.

**Comment by UnixJunkie** [comment]
OK, the PR was accepted:
https://github.com/ocaml-batteries-team/batteries-included/pull/827
