### ISSUE TITLE
BatList.count_matching

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#815]
Specification:

    val BatList.filter_count ('a -> bool) -> 'a list -> int

Like BatList.filter, except that we don't care about the elements that satisfy the given predicate. We just
want to know how many there are.
More efficient than: L.length (L.filter p l) since it will go through the list only once.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/pull/816

**Comment by c-cube** [comment]
I'm feeling a bit uneasy about all these new combined functions. At some point, isn't it much cleaner to have a **fast** iterator type, and to use it in this end?
In containers I'd definitely use `List.to_seq l |> Sequence.filter p |> Sequence.length`. Flambda should compile this into an inlined `List.iter` with a if test and a counter (although benchmarking is always more informative than my intuition).

**Comment by UnixJunkie** [comment]
Personally (but it is a matter of taste), I prefer to read (1):

    let n = L.filter_count is_active molecules in

over (2)

    let n = L.to_seq molecules |> S.filter is_active |> S.length in

and I even prefer (3); let's say <.> is the composition operator

    let n = (L.length <.> L.filter is_active) molecules in

over (2).

I think (1) is the most readable.

**Comment by c-cube** [comment]
Even then, internally `filter_count` could be implemented in this concise way… and you'll never write all the useful combinations! :)

**Comment by tchajed** [comment]
I'm not sure if it should be added, but can it at least be called `BatList.count_matching` rather than `BatList.filter_count`?

**Comment by UnixJunkie** [comment]
in the same vain, we miss filter_map

**Comment by UnixJunkie** [comment]
I am closing because there is no consensus.
If someone wants to send another implementation, this could be reopened.

**Comment by UnixJunkie** [comment]
I need the exact same thing for arrays now, which hints this might be a quite useful feature.

**Comment by UnixJunkie** [comment]
The PR was merged. We need the same feature in BatArray now.
