### ISSUE TITLE
Implement Array.of_list_rev

### ISSUE THREAD

**Issue by madroach** [ocaml-batteries-team/batteries-included#820]

**Comment by UnixJunkie** [comment]
Array.of_list (List.rev l)

**Comment by UnixJunkie** [comment]
let array_of_list_rev = function                                            
      | [] -> failwith "empty list"                                             
      | (x :: xs) as l ->                                                       
        let n = List.length l in                                                
        let res = Array.make n x in                                             
        List.iteri (fun i x ->                                                  
            res.(n - (i +1)) <- x                                               
          ) l;                                                                  
        res

**Comment by UnixJunkie** [comment]
I am closing this, because I don't think we will add such a constructor to all modules with an of_list function.
If I'm wrong, other maintainers are welcome to reopen this issue.
