### ISSUE TITLE
we miss Array.split

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#823]
for the semantics, I mean the ones from the List module.
Having them would allow to easily change list-using code into array-using code.

I can add them if this is judged useful by other maintainers.

**Comment by UnixJunkie** [comment]
I need to code them anyway ...

**Comment by gasche** [comment]
Works with me, although I think that `DynArray` would be a better structure to use for these operations -- and that they will be easier to implement there.

I think that a good way to write `partition` is to create a boolean array with `Array.map pred t`, compute the length of the two required array from it, and then create the two arrays with just the right size. Accumulating elements in a list is likely to be slightly slower, and no easier to write.

**Comment by UnixJunkie** [comment]
I may look into DynArray later, but I already have code for Array.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/pull/826

**Comment by UnixJunkie** [comment]
but fortunately, we already have Array.partition (I was wrong about this one)
