### ISSUE TITLE
range functions have unnecessarily different signatures?

### ISSUE THREAD

**Issue by mars0i** [ocaml-batteries-team/batteries-included#824]
`List`, `LazyList`, and `Enum` include `range` functions that more or less do the same thing in their respective sequence representations, but they have unnecessarily different interfaces, requiring one to remember or look up each one in order to use it.
```ocaml
# BatList.range;;
- : int -> [< `Downto | `To ] -> int -> int list = <fun>
# BatLazyList.range;;
- : int -> int -> int BatLazyList.t = <fun>
# BatEnum.range;;
- : ?until:int -> int -> int BatEnum.t = <fun>
```
`List.range` allows the sequence to be descending, specifying a direction is required with the `` `To``/`` `Downto`` argument.  (Personally, I don't like the required direction argument, but it's convenient to be able to make a descending list.)  `LazyList` and `Enum` don't allow descending sequences, which might be convenient.

`Enum` allows an infinite sequence beginning with the required `int` argument.  This functionality obviously isn't useful for `List`, but it might be useful for `LazyList` too.

(`BatSeq` doesn't include a `range` function, it appears.  I have no opinion about whether one would be useful.)

In case comparisons are helpful:

`Containers` includes two simple range functions.   They both take two required `int` arguments--nothing else--but differ in that one doesn't include the outer index (`CCList.range' 0 5` = `[0;1;2;3;4]`), and both produce descending lists automatically if the first argument is greater than the second.  `Containers` also has `range_by` function that requires a `step` parameter.

`Core`'s `List.range` has options to allow inclusive or exclusive behavior at either end of the list, and a step parameter (called `stride`):
```
# Core.List.range;;
- : ?stride:int ->
    ?start:[ `exclusive | `inclusive ] -> ?stop:[ `exclusive | `inclusive ] -> int -> int -> int list
```
This function doesn't allow descending sequences.

**Comment by mars0i** [comment]
I just looked at the source for `LazyList.range`, and there is code to make decreasing sequences is the first arg is greater than the second, but it's commented out--not sure why.

**Comment by mars0i** [comment]
There's a typo in the ocamldoc for `LazyList.range` btw; it says that "The range is empty if b <= a", but when `a` = `b`, a single-element lazy list is returned, which is what makes sense given that `a` and `b` are included in the returned range.

**Comment by mars0i** [comment]
I don't want to submit a PR if the interfaces need to be harmonized, but there's a simple strategy for including descending sequences and an optional `step` argument for `LazyList.range`:
```ocaml
let range ?(step=1) start stop = 
  if start = stop then make 1 start
  else let adjust_by, ineq =
    if stop > start then (+), (>) else (-), (<)
  in let rec aux curr stop' =
     if ineq curr stop' then nil
     else lazy (Cons (curr, aux (adjust_by curr step) stop'))
  in aux start stop
```

**Comment by UnixJunkie** [comment]
I am closing this.
If you want, you can send a PR to improve LazyList.
Though, personally I never use this module and even think that it should be dropped one day, with other
programming-error-prone modules that very few people use.

**Comment by mars0i** [comment]
OK.  I may submit PRs.   As for the future, do what you want with Batteries, but I would be disturbed to see it taken out.   If it isn't in Batteries, it ought to be somewhere.  afaik Core and Containers don't have anything similar.  (For me the existence of `LazyList` is actually one of the main factors that makes Batteries my library of choice.  `LazyList` is built into the core of my main project.)   Maybe lazy sequences aren't popular in the OCaml at present, and maybe they never will be, but I hope that Ocaml will always be a big tent.   Lazy sequences aren't just for Haskellers and other people who want everything lazy, as Clojure shows.  OCaml is and I hope will be bigger and more valuable than a language for the projects for which it has most often been used.

**Comment by c-cube** [comment]
There's actually a small module for lazy lists in containers, but it's not well developed. The API is quite minimal. I think suspension lists (`'a t = unit -> Nil | Cons of 'a * 'a t`) are better suited to OCaml, and am writing such a library right now.
