### ISSUE TITLE
bisect is not supported for OCaml 4.06

### ISSUE THREAD

**Issue by nekketsuuu** [ocaml-batteries-team/batteries-included#835]
[The `opam` file](https://github.com/ocaml-batteries-team/batteries-included/blob/34885121fb68447a4b9796d6cd8f2cd34f908ee1/opam#L21) says that `batteries` needs `bisect` for testing. However, bisect is not supported for OCaml 4.06 (ocaml/opam-repository#10751).

In fact, `opam install -t batteries` failed under OCaml 4.06.0 whereas `opam install batteries` succeeded.

```sh
$ opam switch show
4.06.0
$ opam reinstall -t batteries
The following dependencies couldn't be met:
  - batteries -> bisect
Your request can't be satisfied:
  - bisect is not available because your system doesn't comply with ocaml-version < "4.06.0".

No solution found, exiting
```

**Comment by gasche** [comment]
Thanks for the report!

We should port bisect to 4.06, migrate to ppx_bisect, or disable coverage testing, whichever is easier.

**Comment by rixed** [comment]
FWIW: http://bugs.x9c.fr/view.php?id=140

**Comment by UnixJunkie** [comment]
I guess 'opam reinstall batteries' would work.
I guess the -t flag forces bisect to be required.

**Comment by UnixJunkie** [comment]
@xclerc

**Comment by gasche** [comment]
This was a two-lines change: https://github.com/ocaml/opam-repository/pull/11472

**Comment by nekketsuuu** [comment]
Thanks to gasche's PR, now `opam reinstall -t batteries` works on OCaml 4.06.0. Thank you all :)

**Comment by rixed** [comment]
Given that:

1. the source code for bisect is not easy to patch (using darc on a private repo with no quick way to submit patch),
2. xclerc does not seems to respond to github or even his own Mantis bugtracker fast enough for us (at least these days),
3. I believe no one ever paid attention to any code coverage tool

I suggest this dependency be dropped and will be happy to provide a patch doing just that if everyone agrees.

**Comment by gasche** [comment]
Yes, I'm fine with this as well. I did the work of implementing bisect support in Batteries, but we never really started to use coverage information (I think the constraint that any changed or added code must come with tests is enough in practice), so dropping bisect support is fine. If anyone was amused to re-introduce it (it was not a lot of work in the first place), of course bisect_ppx would be a wiser choice today.

**Comment by UnixJunkie** [comment]
I'm also in favor of cutting dependencies and simplifying our build system. Great suggestion.
