### ISSUE TITLE
BatOo should be removed

### ISSUE THREAD

**Issue by murmour** [ocaml-batteries-team/batteries-included#848]
BatOo simply re-exports undocumented functionality from the CamlInternalOO module of the standard library. Does it really have place in Batteries? Is it necessary to have a dependency on undocumented compiler internals?

Those poor souls who really need this magic (if any such user exists at all), can get it in the standard library.

Shall I send a PR that removes BatOo?

**Comment by UnixJunkie** [comment]
How do we deprecate something?
Removing is not deprecating.

**Comment by murmour** [comment]
I assumed removing to be a radical form of deprecation. The PR title is changed for clarity.
