### ISSUE TITLE
What about iterators for the option-type?

### ISSUE THREAD

**Issue by matejkosik** [ocaml-batteries-team/batteries-included#853]
[In the Coq codebase](https://github.com/coq/coq/blob/master/clib/option.mli#L62-L103), I've seen some iterators for the `option`-type. Weird as they initially may seem, I've started to like them and I use them.

I am wondering, whether they could be added to batteries.

What do you think?

**Comment by gasche** [comment]
We already have various iterators in [BatOption](http://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatOption.html), but things that are missing could be added of course -- provided their interface is consistent to iterators in other Batteries modules.

**Comment by matejkosik** [comment]
Ok. I'll prepare a pull-request for `Option.iter`.
