### ISSUE TITLE
missing plugin variable in META

### ISSUE THREAD

**Issue by arlencox** [ocaml-batteries-team/batteries-included#866]
It seems to me that the following lines should be added to META so that batteries can be dynamically loaded with findlib's dynamic loading facility (Fl_dynload).
```
plugin(byte)       ="batteries.cma"
plugin(byte,mt)    +="batteriesThread.cma"
plugin(native)     ="batteries.cmxs"
plugin(native,mt)  +="batteriesThread.cmxs"
```
This feature is documented here: http://projects.camlcity.org/projects/dl/findlib-1.8.0/doc/ref-html/r759.html

**Comment by gasche** [comment]
That sounds reasonable (I haven't checked the details yet), would you send a Pull Request to do the change yourself?
