### ISSUE TITLE
Uniform API for Array and DynArray

### ISSUE THREAD

**Issue by andrepd** [ocaml-batteries-team/batteries-included#868]
I'm new to contributing to Batteries. I see that the API for BatArray has many more useful functions than BatDynArray, which in comparison is much more sparse, even though nearly all functionality of the former is applicable to the latter. Is there a reason for this? If this is not intentional, am I okay to correct it (port Array functions into DynArray)?

**Comment by gasche** [comment]
This is a historical accident. I think that in adding more features to DynArray is welcome -- they have to come with tests, though. Please be aware that Dynarray is harder to program because it relies, internally, on an unsafe trick for efficiency reasons (if you are curious about this, you may find the yet-unresolved PR #847 interesting).

**Comment by andrepd** [comment]
I've got the patch nearly done, however there are inconsistencies which are only resolved by renaming existing functions. For example, DynArray.make takes an int and creates an empty array preallocated with that number of elements. This differs from the behaviour of Array.make, List.make, String.make, etc (which is to initialize to a value). Am I okay to rename this function (to DynArray.reserve, for instance), and write DynArray.make to match this behaviour?

**Comment by gasche** [comment]
I would rather separate the API-breaking changes from the other. The non-API-breaking changes can go in the next minor release of Batteries, the API-breaking changes have to wait for the next major release.

**Comment by UnixJunkie** [comment]
related to this strangely named PR https://github.com/ocaml-batteries-team/batteries-included/pull/872

**Comment by UnixJunkie** [comment]
@fccm fixed this one

**Comment by fccm** [comment]
There are still the 2 functions:
- `DynArray.delete : 'a t -> int -> unit`
- `BatArray.remove_at : int -> 'a array -> 'a array`

These 2 functions do the same thing, but the argument orders are different, and the function names are different.
Should we:
1) rename and reorder the paramaters for one of these
2) or, create `DynArray.remove_at` and `BatArray.delete` ?

**Comment by UnixJunkie** [comment]
I would prefer that DynArray follows Array, not the other way around.
Is DynArray.delete an old function?

**Comment by UnixJunkie** [comment]
BatDynArray.delete is 13 years old...
Please create an alias for BatDynArray.delete with the same name and interface as BatArray.remove_at.
And let's not add BatArray.delete (BatArray.remove_at was named like this because of BatList.remove_at).

**Comment by fccm** [comment]
I just noticed that there are not only the parameter order that changes, the 2 functions also don't return in the same way.

`BatArray.remove_at` also returns a new array.
`BatDynArray.delete` returns `unit`.

Do you prefer:
```ocaml
let remove_at idx d = delete d idx; d
```
```ocaml
val remove_at : int -> 'a t -> 'a t
(** Alias for [delete] with parameter order that follows [Array.remove_at].

    @since NEXT_RELEASE *)
```
Or:
```ocaml
let remove_at idx d = delete d idx
```
```ocaml
val remove_at : int -> 'a t -> unit
(** Alias for [delete] with parameter order that follows [Array.remove_at].

    @since NEXT_RELEASE *)
```
?

**Comment by UnixJunkie** [comment]
I think BatDynArray.remove_at should return unit.
By the name, it is obvious to me that it is a imperative / modifiable in place data structure.

**Comment by fccm** [comment]
Done with commit a20fbb4193
