### ISSUE TITLE
Incompatible with OCaml 4.07.0

### ISSUE THREAD

**Issue by ncihnegn** [ocaml-batteries-team/batteries-included#871]

**Comment by gasche** [comment]
Yep, we need to test the build with 4.07, fix any issues, and look at porting new 4.07 library functions to make them usables to Batteries users with older versions.

(I'm planning to look at it eventually but right now my hands are full with porting ppx_import to 4.07: https://github.com/ocaml-ppx/ppx_import/pull/25 )

**Comment by gasche** [comment]
This is now fixed by release 2.9.0, which should hopefully hit OPAM reasonably soon. Apologies for the delay...
