### ISSUE TITLE
Consider moving to ocaml-community?

### ISSUE THREAD

**Issue by gasche** [ocaml-batteries-team/batteries-included#878]
The [ocaml-community](https://github.com/ocaml-community/meta) has recently sprung up as a community group committed to adopting and maintaining OCaml software projects that are not being actively developed by their authors anymore.

I think that it is a natural question to wonder whether batteries-included should migrate to ocaml-community. From the start, batteries-included was designed as a non-hierarchical project built for and by "the ocaml community" at learge. I think the people creating the ocaml-batteries-team organization had in mind the same sort of open-ended, non-hierarchical code ownership and evolution that ocaml-community now represents. In practice this vision did not manifest itself through adopting other repositories, but I would say that in a sense Batteries was a pre-github incarnation of the same ideas.

One difference with possibly other projects ending up in ocaml-community today is that Batteries still receives somewhat frequent active contributions; it is not in strict maintenance mode, updating only to fix severe bugs or support newer OCaml releases. However, it is also less active than it was at the beginning, and I think that there is a sense that, in the era of (1) opam making distributing smaller packages easier and (2) the compiler distribution's standard library breaking its decades-old stillness to move fast, the development of big monolithic standard-library overlays may be slowing down calmly and peacefully. (@c-cube's containers may be a counter-example, or maybe has just not reached its slow mode yet.)  

If we decided to move to ocaml-community, and they accepted to take us in, the idea wouldn't be to stop accepting new features or code changes -- this could go on indefinitely -- or to free the current maintainers (@thizanne, @UnixJunkie and myself) from their maintenance responsibilities. I don't actually think that a lot would change in practice. So why am I suggesting to discuss this?

1. I like the name, ocaml-community. It actually reflects what we do better than ocaml-batteries-team.
2. If the ocaml-community people come up with better ways to do CI, build, or renewed enthusiasm about replacing ocamlbuild+prefilter with dune+cppo, we can benefit from that -- or, more likely, be faced pressure to do the work to follow this better approach on our end.
3. It can help more people realize that batteries is a community-owned project, and possibly volunteer to help along with the maintenance.

(I've been feeling guilty about taking more than my usual two weeks to respond to a new OCaml release for 4.07.0, maybe having some more people willing to do this kind of work could help us be more reactive.)

**Comment by c-cube** [comment]
tbh containers is also slowing down, because 1) most of the things I needed are there and 2) I'm trying to focus on logic-related stuff. It might be a normal trend of stdlibs indeed.

**Comment by UnixJunkie** [comment]
I am not against moving to ocaml-community, if other maintainers agree too.
However, it should be clearly flagged that batteries is not an abandoned and unmaintained project.
We have few contributors and maintainers, but we are not dead yet. :)

**Comment by thizanne** [comment]
I also think it could only be beneficial to batteries.

**Comment by UnixJunkie** [comment]
What are the benefits if we do this?

**Comment by UnixJunkie** [comment]
The only mentioned benefit would be to get more help / new contributors.
I doubt it but...

**Comment by c-cube** [comment]
I don't know if ocaml-community has really succeeded in bringing more maintainers to projects (with the possible exception of yojson).

**Comment by UnixJunkie** [comment]
The problem with OCaml is just the size of our user community.
If there were many more OCaml programmers, we would have more open-source contributors too.
Sometimes, I feel our community still have not reached the critical mass, while Haskell has...
