### ISSUE TITLE
we don't have merge in BatHashtbl

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#891]
There is one in JS Base, for example.

**Comment by rixed** [comment]
What should the signature be?

For my own use I have a function taking the optional values from left and right and returning what the result should be (if any), which I guess is as much a map2 than it is a merge:

```ocaml
val hashtbl_merge:
  ('a, 'b) Batteries.Hashtbl.t ->                                                                                                                     
  ('a, 'c) Batteries.Hashtbl.t ->
  ('a -> 'b option -> 'c option -> 'd option) -> ('a, 'd) Batteries.Hashtbl.t
```

**Comment by gasche** [comment]
@rixed This is the same approach used in `BatMap.merge`, so it seems reasonable to reproduce it here.

@UnixJunkie what's the signature in Base?

**Comment by UnixJunkie** [comment]
The signature of rixed looks good.

In Base:
```
val Base.Hashtbl.merge                                                        
    ('k, 'a) t ->                                                               
    ('k, 'b) t ->                                                               
    f:(key:'k key ->                                                            
       [ `Both of 'a * 'b | `Left of 'a | `Right of 'b ] -> 'c option) ->       
    ('k, 'c) t
```

**Comment by UnixJunkie** [comment]
@rixed don't you have some code that you would like to contribute?

**Comment by rixed** [comment]
Sure, will send a PR later today.

Actually, maybe several, as I have a stack of similarly small functions that I think belong to batteries and that are just waiting for me to take some time to write the PRs.

**Comment by UnixJunkie** [comment]
Even better! Thanks!

**Comment by UnixJunkie** [comment]
I had a project using this funny implementation:

```
let to_sorted_list ht =
  List.sort (fun (k1, _v1) (k2, _v2) -> compare k1 k2) (to_list ht)

let merge ht1 ht2 f =
  let n = max (length ht1) (length ht2) in
  let xs = to_sorted_list ht1 in
  let ys = to_sorted_list ht2 in
  let res = create n in
  let maybe_add k maybe_v1 maybe_v2 =
    match f k maybe_v1 maybe_v2 with
    | None -> ()
    | Some v3 -> add res k v3 in
  let rec loop l1 l2 = match l1, l2 with
    | ([], []) -> ()
    | ([], kvs2) ->
      List.iter (fun (k2, v2) -> maybe_add k2 None (Some v2)) kvs2
    | (kvs1, []) ->
      List.iter (fun (k1, v1) -> maybe_add k1 (Some v1) None) kvs1
    | ((k1, v1) :: kvs1, (k2, v2) :: kvs2) ->
      (* process keys in increasing order *)
      if k1 < k2 then
        let () = maybe_add k1 (Some v1) None in
        loop kvs1 l2
      else if k2 < k1 then
        let () = maybe_add k2 None (Some v2) in
        loop l1 kvs2
      else (* k1 = k2 *)
        let () = maybe_add k1 (Some v1) (Some v2) in
        loop kvs1 kvs2 in
  loop xs ys;
  res
```

But, it's probably wrong in case there are several bindings to the same key.
Also, I guess it could make funny things in case compare does funny things.

**Comment by gasche** [comment]
What should `merge` do in the case of repeated values for the same key? A cartesian product? Ignore the older keys? Get (`'a list * 'a list`) arguments? (Have a separate `merge_many` function?)

**Comment by rixed** [comment]
I was thinking of proposing both a merge functions with the above signature, that will ignore duplicate bindings as find does, and a merge_all that will pass a list of left and right binding, similarly to find_all. The user can then achieve whatever behaviour she wants. WDYT?

**Comment by gasche** [comment]
Yes, that sounds like a reasonable design. It should be very clearly documented in `merge` that further keys are ignored/dropped. (We could even consider naming it `merge_one`, but I'm not fully convinced.) I find it a bit irritating that `merge` would be a lossy operation -- we don't have `equal h (merge <the-right-thing> empty h)`, for example.

**Comment by gasche** [comment]
(Well actually we do, depending on how `equal` is defined.)

**Comment by rixed** [comment]
It also depends on the signification of the duplicate bindings. I suspect many times the user expect only the last binding (that the doc calls "the current" binding) to be meaningful, in which case equality should indeed disregard older bindings.
So no definition of "equal" might satisfies everyone.
Actually, in my own use cases, I've found that when I do want to use several bindings per key then the Hashtbl module is not convenient enough to support this use case and I end up binding lists of values instead. Which, BTW, is also faster for many operations (no need to iter through the whole bucket to retrieve all the values).

**Comment by rixed** [comment]
BTW, I just realised that find_all is not tail recursive in the stdlib. Shouldn't we patch tis in batteries? Or can't I read that code?

**Comment by gasche** [comment]
We can patch this in Batteries, copying the internal `Acc` module of BatList.

**Comment by UnixJunkie** [comment]
I've always found it annoying that stdlib's Hashtbl can have several bindings for one key.
I wonder if we could not have faster Hashtbl if this was not supported.
When I actually want several bindings per key, I just use a list for values.
Also, this makes the doc for add and update more complex.
