### ISSUE TITLE
batteries doesn't compile against 4.08.0

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#897]
and quite many places need fixing... :(

**Comment by catalin-hritcu** [comment]
Will the next release support Ocaml 4.08.0? When is that planned?

(batteries is the last package blocking F*  from supporting 4.08.0)

**Comment by XVilka** [comment]
@catalin-hritcu see https://github.com/ocaml-batteries-team/batteries-included/issues/903

**Comment by UnixJunkie** [comment]
The current master branch supports it.

**Comment by UnixJunkie** [comment]
So yes, the next release will.

**Comment by gasche** [comment]
@UnixJunkie just finished pushing the release out, so now Batteries supports 4.08 :-)
