### ISSUE TITLE
Option.only_if : bool -> (unit -> 'a) -> 'a option

### ISSUE THREAD

**Issue by jrochel** [ocaml-batteries-team/batteries-included#902]
How would people feel about this function? I'll file a PR if no-one minds.

**Comment by UnixJunkie** [comment]
Why not. But maybe a more generic interface is advisable:
```
val only_if: bool -> ('a -> 'b) -> 'b option
```
Maybe other maintainers will chime in.

**Comment by rixed** [comment]
> ```
> val only_if: bool -> ('a -> 'b) -> 'b option
> ```

@UnixJunkie : You mean
```
val only_if: bool -> ('a -> 'b) -> 'a -> 'b option
```

In practice and FWIW I observed in my own code that assuming unit yield more compact code, so I tend to prefer @jrochel version.

**Comment by UnixJunkie** [comment]
Ok. Please send ocamldoc and unit tests along with your proposal.

**Comment by UnixJunkie** [comment]
No PR? :)

**Comment by UnixJunkie** [comment]
Still no PR?

**Comment by UnixJunkie** [comment]
No PR and for too long.
