### ISSUE TITLE
rm the _oasis file

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#906]
anyone against this?
Then simplify release.md.

**Comment by UnixJunkie** [comment]
apparently the opam build uses the setup.ml file generated by oasis.
I don't know why, but I feel that if we could get rid of it, that would be nice.
I.e. we cut permanently the dependency to oasis.

**Comment by UnixJunkie** [comment]
If some maintainers are against this, please raise your hand.

**Comment by gasche** [comment]
I think it's perfectly fine to remove the `_oasis` if we can have a working build/install process without it. Relatedly, one should probably think of switching to dune, which would provide some similar services to Oasis (in particular, an easy way to build the docs).

**Comment by UnixJunkie** [comment]
The current _oasis file is just a wrapper calling our Makefile... So, it seems completely superfluous.
But removing it should be done with care, and we should grep for oasis and _oasis every where...

**Comment by UnixJunkie** [comment]
I would also love to switch to dune.
It is tracked in another issue: https://github.com/ocaml-batteries-team/batteries-included/issues/738

**Comment by UnixJunkie** [comment]
also look for occurences of setup.ml; a file which is generated by oasis

**Comment by UnixJunkie** [comment]
it also generate the META file from the META.in file; apparently just to update the version tag

**Comment by UnixJunkie** [comment]
compiles on 4.02.3

**Comment by UnixJunkie** [comment]
(running the unit test suite requires ocaml 4.03.0 at least because of qcheck-ounit, I believe)

**Comment by UnixJunkie** [comment]
compiles and all tests are passing w/ ocaml 4.13.1

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/issues/1081

**Comment by UnixJunkie** [comment]
I think the generation of the META file should be delegated to the myocamlbuild.ml script.
