### ISSUE TITLE
BER MetaOCaml cannot compile batteries 

### ISSUE THREAD

**Issue by rixed** [ocaml-batteries-team/batteries-included#908]
Because of the `>.` operator from BatSet.Infix.
I'd like to rename '<.' and '>.' into '<<' and '>>' for instance, as a breaking change in the next major release.
WDYT?

**Comment by UnixJunkie** [comment]
There is a slight problem: someone should really invest significant manpower in the next _major_ release, which is very long overdue.
I am OK with your proposition, though.

**Comment by rixed** [comment]
Is there a list of things to be done for the next release written down somewhere, or are we speaking about [those bugs tagged for next release](https://github.com/ocaml-batteries-team/batteries-included/issues?q=is%3Aissue+is%3Aopen+label%3A%22for+next+major+release%22) ?

**Comment by UnixJunkie** [comment]
When I was triaging our issues list, yes I tagged them as you found out.

**Comment by UnixJunkie** [comment]
We also have PRs with this kind of tag:
https://github.com/ocaml-batteries-team/batteries-included/pulls?q=is%3Aopen+is%3Apr+label%3A%22for+next+major+release%22

**Comment by rixed** [comment]
Good to know that the bug tracker is reliable in this regard. Will start to work my way through the list, as many seems easy enough.

**Comment by rixed** [comment]
Fixed by 9d3ab53cc06f2aee0920c6b350b3c297d00f0370
