### ISSUE TITLE
make a last 2.x release

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#928]

**Comment by rixed** [comment]
Do you want me to do it?

**Comment by UnixJunkie** [comment]
Well, any maintainer/contributor is welcome.

**Comment by rixed** [comment]
Hoping that the release.md doc is up to date, I'm going to do this now.

**Comment by rixed** [comment]
Note that qtest and/or qcheck are not installable via opam for many older supported ocaml versions. That's a data point in favor of keeping this kind of tools within batteries next time.

If I had only one wish: we should do away with maintaining a changelog, a process that's manual, boring and largely useless.

**Comment by UnixJunkie** [comment]
Well, there is a whole website about changelogs only (probably from the same people that did semantic versioning).
They are meant for humans, i.e. the clients of our dear library.
The fact that we ask contributors to update the changelog is supposed to make its maintenance easier for us.

**Comment by UnixJunkie** [comment]
this is not tagged yet

**Comment by UnixJunkie** [comment]
I am checking some things.
Then I will tag and send a PR into opam-repository.

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-repository/pull/15543

**Comment by UnixJunkie** [comment]
PR was merged

**Comment by rixed** [comment]
Thank you.
My plan was to do the remaining bits once the PR was approved.
