### ISSUE TITLE
BatBuffer: No way to add BatSubstring.t

### ISSUE THREAD

**Issue by OhadRau** [ocaml-batteries-team/batteries-included#934]
Not sure if there's some reason behind this, but it's seemingly impossible to add a BatSubstring to a BatBuffer right now. Further, BatBuffer.add_substring is named confusingly because of that. Am I missing something here?

**Comment by UnixJunkie** [comment]
You can send a PR to add what is missing.
Maybe discuss your proposed interface first.

**Comment by UnixJunkie** [comment]
A pull request would be welcome.

**Comment by OhadRau** [comment]
Hi, sorry about disappearing there, I had my Github notifications disabled for a while and didn't see your first message. Since it's been a while since I opened the issue I took a quick look at the docs and [saw that `BatSubstring` is only available as part of `Incubator`](https://github.com/ocaml-batteries-team/batteries-included/blob/879c49663126702ce0388df4b0fb01303f184810/build/intro.text#L71-L77). Just want to confirm, this is no longer the case right? In [the `Incubator` module declaration](https://github.com/ocaml-batteries-team/batteries-included/blob/f6f11fa5ca55bcb35acdc1cbcf15f5cf777d95e0/src/batteries.mlv#L171-L175) it didn't seem like it was present.

Anyways, I'm trying to think through a good interface before I open a PR. `BatBuffer.add_substring` is of course the ideal but would be a breaking change and it seems like `BatBuffer.add_batsubstring` doesn't match the style of the rest of the code. It also seems like the ideal is to keep the `add_` prefix to stay consistent. With that in mind, here's a few possibilities I've thought of:

* `BatBuffer.add_substring_` or `BatBuffer.add_substring'` since these are closest to the "correct" name
* `BatBuffer.add_existing_substring` or `BatBuffer.add_precomputed_substring` is a bit verbose, but meant to convey the idea that this substring value already exists
* `BatBuffer.add_substring_value` or `BatBuffer.add_substring_val` feel more reasonable here, but also are a little confusing since we don't add the `_value`/`_val` suffix for other types
* `BatBuffer.add_string_slice` is my favorite, but would make the most sense if we create a `StringSlice` alias for `BatSubstring`

For what it's worth, I think it would be desirable to define some kind of consistent naming scheme for this `BatSubstring.t` type, as the `substring` name is used interchangeably for both concepts right now (a sub-_string_ or a substring value)

Any thoughts on those names? Specifically the idea of going for `StringSlice`? Or do you have any other ideas that might be better?

**Comment by UnixJunkie** [comment]
let's say your function is named add_X, then what is the type signature you are proposing?

**Comment by OhadRau** [comment]
I was planning to keep it consistent with the other functions in that module:
`val add_X : t -> BatSubstring.t -> unit`

**Comment by UnixJunkie** [comment]
Ok, please send your PR.
I would be OK with add_substring' as the name, but other maintainers might disagree.
We can still change the name later, before merging, so not a big deal.

**Comment by OhadRau** [comment]
Hmm just taking a look at the code now and looks like this would create a circular dependency since `BatSubstring` references `BatIO` => `BatPrintf` => `BatBuffer` (=> `BatSubstring` if I add this change). Is there a typical way that Batteries takes care of those? Would rather not make a mess of things here while I fix it

**Comment by UnixJunkie** [comment]
Well, maybe BatSubstring could have such a function (add_to_buffer?) then, if BatSubstring already depends on BatBuffer.
