### ISSUE TITLE
Support OCaml 4.10

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-batteries-team/batteries-included#935]
Currently Batteries is tagged as not supporting OCaml 4.10 and the first better is on its way. Looking at the output of `git diff 4.09.0..4.10 -- stdlib/*.mli`, very few functions have been added to the standard library so it should not be too much work I'm guessing (modulo some C API change).

**Comment by UnixJunkie** [comment]
Happy new year!
Thanks a lot for the PR.
It should be merged shortly.
