### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by rixed** [ocaml-batteries-team/batteries-included#937]
Shouldn't we merge in the few PRs that were waiting for v3 and then ship the first v3 release?

**Comment by UnixJunkie** [comment]
Of course.

**Comment by UnixJunkie** [comment]
There are not many:
https://github.com/ocaml-batteries-team/batteries-included/pulls?q=is%3Aopen+is%3Apr+label%3A%22for+next+major+release%22
And I suspect some are not mergeable at all.

**Comment by rixed** [comment]
The only three PR flagged `for next release` (https://github.com/ocaml-batteries-team/batteries-included/pull/729 because of cppo, https://github.com/ocaml-batteries-team/batteries-included/pull/554, https://github.com/ocaml-batteries-team/batteries-included/pull/501) seems not to be ready, so I'm going to release with what has been merged as of today.
It's a bit sad for that last one, though, but I have no time to look into this ATM and compatibility with latest OCaml compiler seems more important.
