### ISSUE TITLE
BatResult.t = Stdlib.result

### ISSUE THREAD

**Issue by jrochel** [ocaml-batteries-team/batteries-included#938]
Shouldn't there be a type equality ? Otherwise one is forced to continually convert between the types.

**Comment by UnixJunkie** [comment]
Do you have a PR to propose?

**Comment by jrochel** [comment]
I've become quite reticent concerning PRs to any OCaml packages as the community turns out to be what I would consider extremely conservative to change. This is why I have made it a habit feel to out the terrain first (as I'm doing with this issue).

**Comment by UnixJunkie** [comment]
I agree that OCaml's stdlib is "extremely conservative" and same for several venerable OCaml hackers. However, batteries is not the stdlib.
If there is a technical fix for the problem you observe, I would be happy to see the fix you propose; hence my request for a PR.

**Comment by UnixJunkie** [comment]
A PR from a helpful contributor was merged.
