### ISSUE TITLE
feature request : Add find_option in BatMap.S interface

### ISSUE THREAD

**Issue by nicoTolly** [ocaml-batteries-team/batteries-included#940]
Currently the module type BatMap.S does not expose the function find_opt: key -> 'a t -> 'a option
which I find convenient sometimes, even if it is easy to implement it as :
let find_opt k m =
try Some (find k m) with
| NotFound -> None

Actually such a function is already implemented as find_option at line 174 of file BatMap.ml (the equivalent function in List is called find_opt). Is there any reason not to expose it ? I can do a PR if this seems ok.

**Comment by gasche** [comment]
Having the function sounds like a good idea. It should be named `find_opt`, to use the same name as the standard library `Map.S` (where `find_opt` is present since OCaml 4.05). Note that the implementation you propose can be improved by using `match .. with exception`:

```
match find k m with
| exception Not_found -> None
| v -> Some v
```

(Here the difference is somewhat minor, but it is clearer in terms of which part of the code precisely may raise the exception.)

**Comment by UnixJunkie** [comment]
I think this code will not compile with old versions of OCaml.

**Comment by nicoTolly** [comment]
What is the policy with regards to backward compatibility ? Which versions of the compiler should I try to run on ? I can't find anything in https://github.com/ocaml-batteries-team/batteries-included/wiki/Developers-Guidelines

**Comment by UnixJunkie** [comment]
Good question.
I think batteries can still compile with 3.12.1 nowadays.
But, maybe the maintainers and/or the batteries users might decide a version number
higher than this as a hard constraint.

**Comment by UnixJunkie** [comment]
For example, the opam package mentions OCaml >= 4.0.0

**Comment by nicoTolly** [comment]
So I did a PR, waiting for your comments (especially on the syntax matter).

**Comment by UnixJunkie** [comment]
PR was merged.
I should updated the ChangeLog...

**Comment by UnixJunkie** [comment]
If you want to be called something else than nicoTolly in the ChangeLog, please let use know.
