### ISSUE TITLE
batteries is not compatible with multicore-OCaml

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#949]
I don't know why, @Sudha247 just mentioned it to me.
If multicore-OCaml turns out to be higher performance than Parmap or so,
maybe we should look into that some day.

**Comment by kayceesrk** [comment]
This incompatibility is because batteries uses the `Gc` module https://github.com/ocaml-batteries-team/batteries-included/blob/73b2085c31666ad8f25d55b5ca5437564d4a0d09/src/batGc.mliv. Some of the fields are no longer present in multicore as the allocator and the collector are different in multicore.

**Comment by thelema** [comment]
Someone could write a new wrapper of all the bat* modules that excludes gc;
such a module could be compatible with multicore.

**Comment by gasche** [comment]
On the simpler "hack" level, our preprocessor could have logic to detect if we are on Multicore or not, and expose different interfaces for Gc in either case, exactly as we do when different OCaml versions don't expose the same interface.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-multicore/ocaml-multicore/issues/323

**Comment by UnixJunkie** [comment]
```
# Sys.ocaml_version;;
- : string = "4.06.1+multicore-dev0"
```

**Comment by UnixJunkie** [comment]
Should we fix this (at the cost of more preprocessing) or wait for multicore-ocaml to become the standard ocaml?

**Comment by UnixJunkie** [comment]
fixed by https://github.com/ocaml-batteries-team/batteries-included/pull/991
