### ISSUE TITLE
batUnix test failure on a busy machine

### ISSUE THREAD

**Issue by vbgl** [ocaml-batteries-team/batteries-included#950]
The test case for `batUnix.sleepf` (https://github.com/ocaml-batteries-team/batteries-included/blob/v3.0.0/src/batUnix.mlv#L61) often fails when run on a busy machine.

What is the purpose of the check `dt <= 0.003`? IMHO it is wrong (`sleepf` is allowed to pause for longer than asked) and should be removed.

**Comment by UnixJunkie** [comment]
Please read from lines 57 to 62 in that file.
Better than removing that test, having this test declared as non critical if failing would be nice.
If someone can send a PR for that, we will be happy to review it.

**Comment by vbgl** [comment]
Thanks for the quick reply. I’m not familiar with your testing infrastructure. Skimming through the documentation of qtest, I couldn’t find how a test can be “declared as non critical”.

**Comment by rixed** [comment]
Indeed I don't think qtest implementd such a notion.
Would it be acceptable to just test that the duration was `< 1.` ? In real world I can indeed imagine how a runnable process would miss a few time slices, but on a usual linux box, for that sleep to return after more than 1s you would need to have more than 10 runnable process with a higher prio and at that point well, maybe the test suite could not terminate at all. And from the point of view of the test it is enough I think to check that fractions of a second are accepted and not silently converted to integers behind the scene.
WDYT?

**Comment by UnixJunkie** [comment]
1) I will send a feature request to qtest.
2) the test can be weakened as dt >= 0.02.
Another remark, people who really want to sleep 1ms or so should use bindings to nano_sleep.

**Comment by UnixJunkie** [comment]
related to https://github.com/vincent-hugot/qtest/issues/56

**Comment by UnixJunkie** [comment]
corrected by https://github.com/ocaml-batteries-team/batteries-included/pull/952

**Comment by UnixJunkie** [comment]
there is still a pending feature request for nano_sleep in extunix
https://github.com/ygrek/extunix/issues/37

**Comment by vbgl** [comment]
Thanks for the fix.
