### ISSUE TITLE
Expose `Map.remove_exn`

### ISSUE THREAD

**Issue by rixed** [ocaml-batteries-team/batteries-included#954]
Currently the only function that removes an element from a Map and let the caller know if that element was indeed in the Map is `extract`, that also returns the removed element, which might not be needed.

I've seen cases where remove_exc is exactly what was needed. It is already defined, just not declared. Given we already have many visible `_exc` variant of functions dealing with containers, I think it makes sense to also expose Map.remove_exc.

**Comment by UnixJunkie** [comment]
It is OK with me, just check if _exn is not the suffix we usually use.
I think _exn is the suffix in Jane Street libraries also.

**Comment by UnixJunkie** [comment]
No PR? :)

**Comment by rixed** [comment]
Will send one later today.

**Comment by rixed** [comment]
We have `List.fold_exc` and `RefList.find_exc` but usually we indeed use the `_exn` suffix so I will use that, and propose another PR to add aliases to the `_exc` functions.
