### ISSUE TITLE
{BatArray|BatList}.rev_sort

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#960]
In highly used modules, like BatArray and BatList,
it could be useful to implement rev_sort, in addition to the existing sort.

I can send a PR if others like it too.

**Comment by gasche** [comment]
BatOrd has `rev_*` functions to reverse a comparison, so `Array.rev_sort cmp foo` could be written `Array.sort (BatOrd.rev_comp cmp) foo`.

**Comment by UnixJunkie** [comment]
Yes, if we have a flip function like in Haskell, that's easy to write.
But, what code do you prefer to read:
```
Array.rev_sort cmp a
```
or
```
Array.sort (BatOrd.rev_comp cmp) a
```

**Comment by thizanne** [comment]
> Yes, if we have a flip function like in Haskell, that's easy to write.

We do.

`Array.sort (flip cmp) a` seems fine to me?

**Comment by UnixJunkie** [comment]
I will read about what is in BatPervasives one more time... :)
