### ISSUE TITLE
DynArray interface documentation

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#984]
since tags are missing for many new functions

**Comment by UnixJunkie** [comment]
the interface is probably not synchronized with the implementation regarding the type of exception thrown in each case

**Comment by UnixJunkie** [comment]
@andrep @fccm

**Comment by fccm** [comment]
Half of the functions from this module raise `Pervasives.Invalid_arg`, and the others `DynArray.Invalid_arg`.
Maybe we could uniformise it.
Then which one would you prefer to keep?

**Comment by UnixJunkie** [comment]
The problem is that this is a breaking change.
Old functions which were already throwing an exception should not have its type changed.
If recently introduced functions introduced Pervasives.invalid_arg, it would be better if we stick to the exception
that was already present in the module (DynArray.Invalid_arg).

**Comment by UnixJunkie** [comment]
thanks to @fccm
